# -*- coding: utf-8 -*-
"""RL_Assignment3_DoubleQ.ipynb

Automatically generated by Colab.

"""

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.distributions import Categorical
import gymnasium as gym
from collections import deque
import random
import matplotlib.pyplot as plt
import argparse

# --- Neural Network definitions --- #
# Actor network
class Actor(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(Actor, self).__init__()
        self.fc1 = nn.Linear(input_dim, 128)
        self.policy = nn.Linear(128, output_dim)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        policy_prob = self.policy(x)
        policy = torch.softmax(policy_prob, dim=-1)
        return policy


# Critic network
class Critic(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(Critic, self).__init__()
        #q1
        self.fc1 = nn.Linear(input_dim, 128)
        self.reward1 = nn.Linear(128, output_dim)

        #q2
        self.fc2 = nn.Linear(input_dim, 128)
        self.reward2 = nn.Linear(128, output_dim)

    def forward(self, x):
        x1 = torch.relu(self.fc1(x))
        q1 = self.reward1(x1)

        x2 = torch.relu(self.fc2(x))
        q2 = self.reward2(x2)
        return q1,q2


def select_action(actor, state):
    state = torch.FloatTensor(state).unsqueeze(0)
    with torch.no_grad():
        action_probs = actor(state)
        dist = Categorical(action_probs)
        action = dist.sample().item()

    return action


# Replay buffer
class ReplayBuffer:
    def __init__(self, capacity):
        self.buffer = deque(maxlen=capacity)

    def push(self, state, action, reward, next_state, done):
        self.buffer.append((state, action, reward, next_state, done))

    def sample(self, batch_size):
        batch = random.sample(self.buffer, batch_size)
        state, action, reward, next_state, done = zip(*batch)
        return (
            torch.FloatTensor(state),
            torch.LongTensor(action),
            torch.FloatTensor(reward),
            torch.FloatTensor(next_state),
            torch.FloatTensor(done)
        )

    def __len__(self):
        return len(self.buffer)


#----------------------------------------------------------------------------------------------------------------#
# Main SAC SingleQ training loop
#----------------------------------------------------------------------------------------------------------------#
def main(args):
    # Hyperparameters
    gamma = 0.99
    alpha = args.alpha
    learning_rate = 0.001
    batch_size = 64
    buffer_capacity = 10000
    max_steps = 10**5
    num_runs = 5

    update_every = 10

    env = gym.make('CartPole-v1')
    state_dim = env.observation_space.shape[0]
    action_dim = env.action_space.n

    #Create replay buffer
    replay_buffer = ReplayBuffer(buffer_capacity)

    #Create networks and optimizers
    actor = Actor(state_dim, action_dim)
    critic = Critic(state_dim, action_dim)

    optimizer_actor = optim.Adam(actor.parameters(), lr=learning_rate)
    optimizer_critic = optim.Adam(critic.parameters(), lr=learning_rate)

    global_records = []
    #Training loop
    for run in range(num_runs):
        steps = 0
        run_record = []

        while steps < max_steps:
            state, _ = env.reset()
            done = False
            rewards = []

            while not done:
                action = select_action(actor, state)
                next_state, reward, terminated, truncated, _ = env.step(action)
                done = terminated or truncated

                #Store transition in replay buffer
                replay_buffer.push(state, action, reward, next_state, float(done))

                state = next_state
                rewards.append(reward)
                steps += 1

                # Update networks if enough samples
                if len(replay_buffer) >= batch_size and steps % update_every == 0:
                    #Sample batch
                    state_batch, action_batch, reward_batch, next_state_batch, done_batch = replay_buffer.sample(batch_size)

                    #Update critic
                    with torch.no_grad():
                        next_probs = actor(next_state_batch)
                        next_log_probs = torch.log(next_probs + 1e-8)  #Add small constant to prevent log(0)

                        # Clipped double-Q
                        q1_next, q2_next = critic(next_state_batch)

                        q1_next_value = next_probs * q1_next
                        q2_next_value = next_probs * q2_next
                        min_q_next = torch.min(q1_next_value, q1_next_value)

                        entropy_term = alpha * next_log_probs
                        weighted_q_values = next_probs * (min_q_next - entropy_term)
                        soft_q = weighted_q_values.sum(dim=1)

                        # Target Q-value
                        target_q = reward_batch + gamma * (1 - done_batch) * soft_q

                    # Current Q-values
                    q1_current, q2_current = critic(state_batch)

                    q1_action = q1_current.gather(1, action_batch.unsqueeze(1)).squeeze(1)
                    q2_action = q2_current.gather(1, action_batch.unsqueeze(1)).squeeze(1)

                    # Critic loss
                    q1_loss = F.mse_loss(q1_action, target_q)
                    q2_loss = F.mse_loss(q2_action, target_q)
                    critic_loss = q1_loss + q2_loss

                    # Update critic
                    optimizer_critic.zero_grad()
                    critic_loss.backward()
                    optimizer_critic.step()

                    # Update actor
                    probs = actor(state_batch)
                    log_probs = torch.log(probs + 1e-8)
                    q1_values, q2_values = critic(state_batch)
                    min_q_values = torch.min(q1_values, q2_values)

                    # Actor loss
                    inside_term = alpha * log_probs - min_q_values
                    actor_loss = (probs * inside_term).sum(dim=1).mean()

                    # Update actor
                    optimizer_actor.zero_grad()
                    actor_loss.backward()
                    optimizer_actor.step()
                    if steps >= max_steps:
                        done = True
            total_reward = sum(rewards)

            run_record.append((steps, total_reward))
            print(f"Run: {run+1}, Global Step: {steps}, Episode Reward: {total_reward}")


        global_records.append(run_record)

    plt.figure(figsize=(12, 6))
    all_steps = []
    all_rewards = []
    for run_idx, run_record in enumerate(global_records):
        steps, rewards = zip(*run_record)
        all_steps.append(steps)
        all_rewards.append(rewards)
        plt.plot(steps, rewards, label=f'Run {run_idx+1}', alpha=0.6)

    min_episodes = min(len(r) for r in all_steps)
    avg_steps = [np.mean([all_steps[r][i] for r in range(num_runs)]) for i in range(min_episodes)]
    avg_rewards = [np.mean([all_rewards[r][i] for r in range(num_runs)]) for i in range(min_episodes)]
    plt.plot(avg_steps, avg_rewards, color='black', linewidth=3, label="Average Reward")
    plt.xlabel('Global Training Steps')
    plt.ylabel('Episode Reward')
    plt.title('Learning Curve (Episode Reward vs. Global Steps)')
    plt.legend()
    plt.show()

    def moving_average(values, window=50):
        return np.convolve(values, np.ones(window)/window, mode='valid')

    plt.figure(figsize=(12, 6))
    all_smoothed_steps = []
    all_smoothed_rewards = []
    for run_idx, run_record in enumerate(global_records):
        steps, rewards = zip(*run_record)
        smoothed_rewards = moving_average(rewards, window=10)
        smoothed_steps = moving_average(steps, window=10)
        all_smoothed_steps.append(smoothed_steps)
        all_smoothed_rewards.append(smoothed_rewards)
        plt.plot(smoothed_steps, smoothed_rewards, label=f'Run {run_idx+1}', alpha=0.6)

    # Compute average smoothed curve using the minimum lengtsh among all runs (more successful runs will have less episodes)
    min_smoothed = min(len(s) for s in all_smoothed_steps)
    avg_smoothed_steps = [np.mean([all_smoothed_steps[r][i] for r in range(num_runs)]) for i in range(min_smoothed)]
    avg_smoothed_rewards = [np.mean([all_smoothed_rewards[r][i] for r in range(num_runs)]) for i in range(min_smoothed)]
    plt.plot(avg_smoothed_steps, avg_smoothed_rewards, color='black', linewidth=3, label="Average Smoothed Reward")
    plt.xlabel('Global Training Steps')
    plt.ylabel('Episode Reward (Smoothed)')
    plt.title('Smoothed Learning Curve (Episode Reward vs. Global Steps)')
    plt.legend()
    plt.show()


if __name__ == "__main__":
  parser = argparse.ArgumentParser(description="SAC SingleQ algorithm")
  parser.add_argument(
    "--alpha",
    type=float,
    default = 0.8,
    help="Alpha, entropy coefficient"
  )
  args = parser.parse_args()
  main(args)