# -*- coding: utf-8 -*-
"""Assignment_2_Task_1_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oKAuS4ysMEbh57zs3L45rHJFK_n7iWFS

# Introduction to Deep Learning

<div style="text-align: right">   </div>


Introduction to Deep Learning (2024) &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;| &nbsp;
-------|-------------------
**Assignment 1, Part 3: Generative Models** | <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/UniversiteitLeidenLogo.svg/1280px-UniversiteitLeidenLogo.svg.png" width="300">


In this notebook we are going to cover two generative models for generating novel images:

1. Variational Autoencoders (**VAEs**)
2. Generative adversarial networks (**GANs**)


<img src="https://lilianweng.github.io/lil-log/assets/images/three-generative-models.png" width="500">


Our notebook is based on [this original notebook](https://colab.research.google.com/drive/16j1EOOp_2butQUNu1EV97VL6a5SioDwt?usp=sharing) provided by the course organizers, but adapted to our dataset and modelling choices.

In task 1.2 we were asked to find a new dataset and use the code from the original notebook, to train both VAE and GAN models.

We chose to **dog faces** dataset from kaggle, since the variance in the dataset is relatively small and we have many observations. The dog faces dataset is a subset of the animals dataset, which has 3 classes: dogs, cats, wild animals. The link to the full dataset is [here](https://www.kaggle.com/datasets/andrewmvd/animal-faces/data).


Note: If you re-run this notebook yourself you might get slightly different images, due to the stochastic nature of the data generation process (even if you set the a seed number).
"""

# Load libraries
import os
os.environ['TF_USE_LEGACY_KERAS'] = '1'

from tqdm import tqdm
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import kagglehub
from PIL import Image
import shutil

"""## Custom Dataset

Download our dataset from Kaggle using the Kaggle API.
"""

# Download the full animals dataset
path = kagglehub.dataset_download("andrewmvd/animal-faces")

print("Path to dataset files:", path)

"""It's easiest to preview the dataset on the kaggle website. For now we will manaually check that the folder exists."""

# Show root folder
!ls /root/.cache/kagglehub/datasets/andrewmvd/animal-faces/versions/1

# Root folder contains train and val folder
!ls /root/.cache/kagglehub/datasets/andrewmvd/animal-faces/versions/1/afhq

# Train folder contains - cats, dogs, wild
!ls /root/.cache/kagglehub/datasets/andrewmvd/animal-faces/versions/1/afhq/train

"""Verify that the images have been loaded into the runtime."""

# Function to dispaly images
def show_nth_jpeg(directory, n=1):
  # Find jpeg image files
  jpeg_files = [f for f in os.listdir(directory) if f.endswith(".jpg")]

  # Display nth image
  image_path = os.path.join(directory, jpeg_files[n])
  img = Image.open(image_path)
  plt.imshow(img)
  plt.axis('off')  # Turn off axis labels
  plt.show()


# Check that dog images exist
directory = '/root/.cache/kagglehub/datasets/andrewmvd/animal-faces/versions/1/afhq/train/dog'
show_nth_jpeg(directory, n = 4)
show_nth_jpeg(directory, n = 5)

"""## Data pre-processing


1.   Only select the dog data from the train and the val folder
2.   Convert the images into .npy so that we can use the data loading function from the original notebook


"""

# Specify source folders that we will be copying
root_folder = '/root/.cache/kagglehub/datasets/andrewmvd/animal-faces/versions/1/afhq/'
source_folders = [os.path.join(root_folder, 'train/dog'),
                  os.path.join(root_folder, 'val/dog')]

# New folder to be copied to
destination_folder = 'my_data'
os.makedirs(destination_folder, exist_ok=True)

# Move files and count them
image_count = 0

for folder in source_folders:
    for file_name in os.listdir(folder):
        if file_name.lower().endswith('.jpg'):
            src_file = os.path.join(folder, file_name)
            dst_file = os.path.join(destination_folder, file_name)
            shutil.move(src_file, dst_file)
            image_count += 1

print(f"Total images moved: {image_count}")

"""Convert the images to 96x96x3.

This is slighlty bigger than the images in the original notebook (64x64x3), so they should hopefully contain more useful information, while still being small enough that running the models will not take too long.
"""

# Convert jpeg to numpy array and resize
def convert_images_to_npy(image_folder, output_file, num_images=5239, img_size = 64):
    # Pre-allocate the NumPy array for images
    image_data = np.zeros((num_images, img_size, img_size, 3), dtype=np.uint8)

    image_index = 0

    for filename in os.listdir(image_folder):
        if filename.endswith(".jpg"):
            image_path = os.path.join(image_folder, filename)

            # Open and resize the image
            img = Image.open(image_path)
            img = img.resize((img_size, img_size))

            # Convert to numpy array
            image_data[image_index] = np.array(img)
            image_index += 1

    # Save as .npy file
    np.save(output_file, image_data)

    print(f"Converted images to '{output_file}'")

# Call the function with final image size of 96x96x3
image_folder = 'my_data'
output_file = 'my_images.npy'
convert_images_to_npy(image_folder, output_file, img_size = 96)

"""This code takes 1 min.

## View dataset

We updated the load function such that scale=F will explicitly scale the images to [0, 1]. Scale=F will scale the images to [-1, 1]. This important as the sigmoid activation function requires [0, 1] and the tanh function requires [-1, 1] outputs. We also changed it to load our dog face data.
"""

def load_real_samples(scale=False):
    # Load dog face data
    X = np.load('my_images.npy',  fix_imports=True,encoding='latin1')
    if scale:
      return (X - 127.5) / 127.5 # Scale means [-1, 1] range
    else:
      return X / 255. # No scale means [0, 1] range

# We will use this function to display the output of our models throughout this notebook
def grid_plot(images, epoch='', name='', n=3, save=False, scale=False):
    if scale:
        images = (images + 1) / 2.0
    for index in range(n * n):
        plt.subplot(n, n, 1 + index)
        plt.axis('off')
        plt.imshow(images[index])
    fig = plt.gcf()
    fig.suptitle(name + '  '+ str(epoch), fontsize=14)
    if save:
        filename = 'results/generated_plot_e%03d_f.png' % (epoch+1)
        plt.savefig(filename)
        plt.close()
    plt.show()


dataset = load_real_samples()
grid_plot(dataset[np.random.randint(0, 1000, 9)], name='Dog dataset (96x96x3)', n=3)

"""# Encoder-Decoder



<img src="https://i2.wp.com/sefiks.com/wp-content/uploads/2018/03/convolutional-autoencoder.png" width="500">

The only change to the encoder-decoder code is the dynamic reshaping in the decoder layer, which is computed as a number of the upsampling layers.

Since the original code uses a stride of 2, the final output of the encoder will be `96 / 2**n_upsampling_layers`, e.g. if we have 3 layers then the input image will be compressed into `96/2^3=12` by 12 image. This image will be the input for the decoder.

The rest of the code is like in the original notebook.
"""

from tensorflow.keras.layers import Dense, Flatten, Conv2D, Conv2DTranspose, Reshape

def build_conv_net(in_shape, out_shape, n_downsampling_layers=2, filters=128, out_activation='sigmoid'):
    """
    Build a basic convolutional network
    """
    default_args=dict(kernel_size=(3,3), strides=(2,2), padding='same', activation='relu')

    input = tf.keras.Input(shape=in_shape)
    x = Conv2D(filters=filters, name='enc_input', **default_args)(input)

    for _ in range(n_downsampling_layers):
        x = Conv2D(**default_args, filters=filters)(x)

    x = Flatten()(x)
    x = Dense(out_shape, activation=out_activation, name='enc_output')(x)

    model = tf.keras.Model(inputs=input, outputs=x, name='Encoder')

    model.summary()
    return model


def build_deconv_net(latent_dim, n_upsampling_layers=2, filters=128, activation_out='sigmoid'):
    """
    Build a deconvolutional network for decoding/upscaling latent vectors

    When building the deconvolutional architecture, usually it is best to use the same layer sizes that
    were used in the downsampling network and the Conv2DTranspose layers are used instead of Conv2D layers.
    Using identical layers and hyperparameters ensures that the dimensionality of our output matches the
    shape of our input images.
    """

    output_size = int(96 / 2**n_upsampling_layers)

    input = tf.keras.Input(shape=(latent_dim,))
    x = Dense(output_size * output_size * 96, input_dim=latent_dim, name='dec_input')(input) # 4 * 4 * 64,
    x = Reshape((output_size, output_size, 96))(x) # This matches the output size of the downsampling architecture # 4,4,64

    default_args=dict(kernel_size=(3,3), strides=(2,2), padding='same', activation='relu')

    for i in range(n_upsampling_layers):
        x = Conv2DTranspose(filters=filters, **default_args)(x)

    # This last convolutional layer converts back to 3 channel RGB image
    x = Conv2D(filters=3, kernel_size=(3,3), padding='same', activation=activation_out, name='dec_output')(x)

    model = tf.keras.Model(inputs=input, outputs=x, name='Decoder')
    model.summary()
    return model

"""## Convolutional Autoencoder



<img src="https://lilianweng.github.io/lil-log/assets/images/autoencoder-architecture.png" width="500">


Playing with a CAE was not part of the assignment. However, the CAE is a great way to illustrate how these two components (convolutional and deconvolutional networks) can be used together to reconstruct images.

The only thing we changed in the code below is adding an additional argument called `n_layers` which controls the number of hidden layers in the decoder and encoder.
"""

def build_convolutional_autoencoder(data_shape, latent_dim, filters=128, n_layers=2):
    encoder = build_conv_net(in_shape=data_shape, out_shape=latent_dim, filters=filters,
                             n_downsampling_layers=n_layers)
    decoder = build_deconv_net(latent_dim, activation_out='sigmoid', filters=filters,
                               n_upsampling_layers=n_layers)

    # We connect encoder and decoder into a single model
    autoencoder = tf.keras.Sequential([encoder, decoder])

    # Binary crossentropy loss - pairwise comparison between input and output pixels
    autoencoder.compile(loss='binary_crossentropy', optimizer='adam')

    return autoencoder


# Defining the model dimensions and building it
image_size = dataset.shape[1:]
latent_dim = 512
num_filters = 128

# Train a CAE with 2 hidden layers instead of 4 hidden layer per encoder-decoder
cae = build_convolutional_autoencoder(image_size, latent_dim, num_filters,
                                      n_layers=2)


## Training the Convolutional autoencoder to reconstruct images
for epoch in range(50):
    print('\nEpoch: ', epoch)

    # Note that (X=y) when training autoencoders!
    # In this case we only care about qualitative performance, we don't split into train/test sets
    cae.fit(x=dataset, y=dataset, epochs=1, batch_size=2) # 64

    samples = dataset[:9]
    reconstructed = cae.predict(samples)
    grid_plot(samples, epoch, name='Original', n=3, save=False)
    grid_plot(reconstructed, epoch, name='Reconstructed', n=3, save=False)

"""Observations:


*   The CAE does a great job at reconstructing the original images
*   A big latent space and a high number of channels results in more accurate reconstructions, compared to a small latent space and number of channels
* I set the batch size such that the model has about 2,500 training examples per epoch
  * This is about the same number of training examples per epoch like the original notebook with the human faces dataset

This code takes about 27 minutes to run.

---
---


# Variational Autoencoders (Task 1.3)

<img src="https://lilianweng.github.io/lil-log/assets/images/vae-gaussian.png" width="500">


We left the code below untouched except for adding a `sampling_layers` argument which controls the number of hidden layers in the encoder-decoder.
"""

class Sampling(tf.keras.layers.Layer):
    """
    Custom layer for the variational autoencoder
    It takes two vectors as input - one for means and other for variances of the latent variables described by a multimodal gaussian
    Its output is a latent vector randomly sampled from this distribution
    """
    def call(self, inputs):
        z_mean, z_var = inputs
        batch = tf.shape(z_mean)[0]
        dim = tf.shape(z_mean)[1]
        epsilon = tf.keras.backend.random_normal(shape=(batch, dim))
        return z_mean + tf.exp(0.5 * z_var) * epsilon

def build_vae(data_shape, latent_dim, filters=128, sampling_layers=2):

    # Building the encoder - starts with a simple downsampling convolutional network
    encoder = build_conv_net(data_shape, latent_dim*2, filters=filters,
                             n_downsampling_layers=sampling_layers)

    # Adding special sampling layer that uses the reparametrization trick
    z_mean = Dense(latent_dim)(encoder.output)
    z_var = Dense(latent_dim)(encoder.output)
    z = Sampling()([z_mean, z_var])

    # Connecting the two encoder parts
    encoder = tf.keras.Model(inputs=encoder.input, outputs=z)

    # Defining the decoder which is a regular upsampling deconvolutional network
    decoder = build_deconv_net(latent_dim, activation_out='sigmoid', filters=filters,
                               n_upsampling_layers=sampling_layers)
    vae = tf.keras.Model(inputs=encoder.input, outputs=decoder(z))

    # Define a custom layer for the KL loss calculation
    class KLLossLayer(tf.keras.layers.Layer):
        def call(self, inputs):
            z_mean, z_var = inputs
            kl_loss = -0.5 * tf.reduce_sum(z_var - tf.square(z_mean) - tf.exp(z_var) + 1)
            # Add the KL loss to the model's losses
            self.add_loss(kl_loss / tf.cast(tf.keras.backend.prod(data_shape), tf.float32))
            return inputs  # Pass through the inputs unchanged

    # Apply the custom layer to z_mean and z_var
    _, _ = KLLossLayer()([z_mean, z_var])

    vae.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3), loss='binary_crossentropy')

    return encoder, decoder, vae

"""Now I will train the VAE model twice:


1.   Use similar architecture/parameter choices to CAE
2.   Use specialised architecture choices to generate the best possible images

### Bad parameter choices

These were based on the CAE, but they did not work out.

In the training function we only sample from the latent space once, so that we can observe the progression of the visualization of the same samples over time.
"""

# Training the VAE model

latent_dim = 512
num_filters = 128

encoder, decoder, vae = build_vae(dataset.shape[1:], latent_dim, filters=num_filters,
                                  sampling_layers=2)

# Always display the SAME 9 random samples
np.random.seed(123)
latent_vectors = np.random.randn(9, latent_dim)

for epoch in range(20):
    vae.fit(x=dataset, y=dataset, epochs=1, batch_size=2) # 8

    # Generate random vectors that we will use to sample from the learned latent space
    coefficient = 6 # 6                                # You can tweak this coefficient to increase/decrease the std of the sampled vectors
    images = decoder(latent_vectors / coefficient)  # Feed the vectors scaled by the coefficient to the model
    grid_plot(images, epoch, name='VAE generated images (randomly sampled from the latent space)', n=3, save=False)

"""Observations:


*   The code produces only grey images
*   This could be the result of different loss functions
  * CAE loss = binary cross entropy loss
  * VAE loss = binary cross entropy loss + KL loss
      * VAE loss learns z_mean and z_log_var values
      * Therefore, the model parameters from the CAE might not be suitable for the VAE

### Good parameter choices

These parameter choices were inspired by looking at existing VAE solutions online such as:



1.   [TF tutorial](https://www.tensorflow.org/tutorials/generative/cvae)
2.   [Medium tutorial 1](https://medium.com/@danielmachinelearning/enhancing-variational-autoencoders-with-students-t-distribution-a-new-approach-to-robustness-and-35c333ba6030)
3. [Medium tutorial 2](https://asokraju.medium.com/part-1-variational-autoencoders-introduction-and-implementation-1ceb47a75cb5)

Based on these tutorials we observed that most architectures used a very small latent space and very few channels. Some used many hidden layers, some used only a few.

These heuristic turned out to be helpful.
"""

# Training the VAE model

latent_dim = 4 # 4 works also
num_filters = 32
encoder, decoder, vae = build_vae(dataset.shape[1:], latent_dim, filters=num_filters,
                                  sampling_layers=2)

np.random.seed(123)
latent_vectors = np.random.randn(9, latent_dim) # Generate 9 random points in the latent space

for epoch in range(20):
    vae.fit(x=dataset, y=dataset, epochs=1, batch_size=2)

    # Generate random vectors that we will use to sample from the learned latent space
    coefficient = 6 # 6                                # You can tweak this coefficient to increase/decrease the std of the sampled vectors
    images = decoder(latent_vectors / coefficient)  # Feed the vectors scaled by the coefficient to the model
    grid_plot(images, epoch, name='VAE generated images (randomly sampled from the latent space)', n=3, save=False)

"""## VAE Interpolation (Task 1.4)

For the interpolation, first generate 2 random vectors in the latent space, x and y. Then compute the difference between x and y. This difference vector spans between the end points of vectors x and y. Now follow allong the span of this distance vector to move from vector x to y.

Finally, upsample/decode all vectors from the latent space into the original space.

I also added 2 seed numbers for reproducible results.
"""

# Create vector x and y
np.random.seed(100) # Remove seed if you want random runs each time
x = np.random.randn(1, latent_dim)

np.random.seed(11) # Remove seed if you want random runs each time
rng = np.random.default_rng()
y = rng.normal(loc=0.0, scale=1.0, size=(1, latent_dim))

# Calculate the difference
diff = y - x

# Interpolation step
alphas = np.linspace(0, 1, 5)
data = np.zeros((5, latent_dim))

for idx in range(5):
    data[idx, :] = x + alphas[idx] * diff

# Upscaling step
coefficient = 3 # 6
images = decoder(data / coefficient)

# Create a figure
plt.figure(figsize=(15, 3))  # Adjust the figure size to fit 5 images

# Subtitles
subtitles = ['x', 'x+0.25(y-x)', 'x+0.5(y-x)', 'x+0.75(y-x)', 'y']

# Plot
num_images = 5
for index in range(num_images):
    plt.subplot(1, num_images, 1 + index)  # 1 row, 5 columns
    plt.axis('off')
    plt.imshow(images[index])
    plt.title(subtitles[index], fontsize=12)

fig = plt.gcf()
fig.suptitle("Interpolation (5 steps from left to right) ", fontsize=14)

plt.show()

"""---

# Generative Adversarial Networks (Task 1.3)



<img src="https://media.springernature.com/original/springer-static/image/chp%3A10.1007%2F978-1-4842-3679-6_8/MediaObjects/463582_1_En_8_Fig1_HTML.jpg" width="500">

We left the code below untouched except for adding a `n_layers` argument which controls the number of hidden layers in the encoder-decoder.



"""

from tensorflow.keras.optimizers.legacy import Adam

def build_gan(data_shape, latent_dim, filters=128, lr=0.0002, beta_1=0.5, n_layers = 3):
    optimizer = Adam(learning_rate=lr, beta_1=beta_1)

    # Usually thew GAN generator has tanh activation function in the output layer
    generator = build_deconv_net(latent_dim, activation_out='tanh', filters=filters,
                                 n_upsampling_layers=n_layers)

    # Build and compile the discriminator
    discriminator = build_conv_net(in_shape=data_shape, out_shape=1, filters=filters,
                                   n_downsampling_layers=n_layers) # Single output for binary classification
    discriminator.compile(loss='binary_crossentropy', optimizer=optimizer)

    # End-to-end GAN model for training the generator
    discriminator.trainable = False
    true_fake_prediction = discriminator(generator.output)
    GAN = tf.keras.Model(inputs=generator.input, outputs=true_fake_prediction)
    GAN.compile(loss='binary_crossentropy', optimizer=optimizer)

    return discriminator, generator, GAN

"""We also left the code below mostly untouched, except for correcting how the samples are displayed. When we ran the original code, matplot lib returned a warning message, saying that the generated images were on the [-1, 1] scale.  However, matplot lib expects images to be either on a [0, 1] or a [0, 255] scale. Therefore, matplot lib clipped the image, resulting in weird looking images.

 In the end, we added a custom function to transform the images from [-1, 1] to [0, 1] so that they can be displayed properly. The function name is `rescale_images`.

 Additionally, we sample from the latent variable space only once, before the training, so that we can observe how the same sample gets better visualzed over the epochs. This is more helpful compared to the original code, where at each epoch a new sample is drawn. In the original code it is less clear how the model is prgressing as the visualization could be changing because of the model or because the new sample is a unrepresentative sample.



"""

def get_batch(generator, dataset, batch_size=64):
    """
    Fetches one batch of data and ensures no memory leaks by using TensorFlow operations.
    """
    half_batch = batch_size // 2

    # Generate fake images
    latent_vectors = tf.random.normal(shape=(half_batch, latent_dim))
    fake_data = generator(latent_vectors, training=False)

    # Select real images
    idx = np.random.randint(0, dataset.shape[0], half_batch)
    real_data = dataset[idx]

    # Combine
    X = tf.concat([real_data, fake_data], axis=0)
    y = tf.concat([tf.ones((half_batch, 1)), tf.zeros((half_batch, 1))], axis=0)

    return X, y


# Rescale from [-1, 1] to [0, 1]
def rescale_images(images):
    return (images + 1) / 2


def train_gan(generator, discriminator, gan, dataset, latent_dim, n_epochs=20, batch_size=64):
    """
    Train the GAN with memory-efficient updates and clear session management.
    """
    batches_per_epoch = dataset.shape[0] // batch_size

    # Always display the same 9 samples
    noise = tf.random.normal(shape=(9, latent_dim))

    for epoch in range(n_epochs):
        for batch in tqdm(range(batches_per_epoch)):
            # Train Discriminator
            X, y = get_batch(generator, dataset, batch_size)
            discriminator_loss = discriminator.train_on_batch(X, y)

            # Train Generator
            latent_vectors = tf.random.normal(shape=(batch_size, latent_dim))
            y_gan = tf.ones((batch_size, 1))
            generator_loss = gan.train_on_batch(latent_vectors, y_gan)

        # Generate and visualize after each epoch
        generated_images = generator(noise, training=False)
        # Rescale images from [-1,1] to [0,1]
        rescaled_images = rescale_images(generated_images.numpy())
        grid_plot(rescaled_images, epoch, name='Generated Images', n=3)

        # Clear backend session to free memory
        tf.keras.backend.clear_session()

"""Now I will train the GAN model twice:


1.   Use similar architecture/parameter choices to the best VAE configurations
2.   Use specialised architecture choices to generate the best possible images for GAN


https://www.tensorflow.org/tutorials/generative/dcgan#create_the_models

## Bad parameter choices

These were based on the best VAE configurations, but didn't work out for the GAN.
"""

## Build and train the model (need around 10 epochs to start seeing some results)

latent_dim = 4
discriminator, generator, gan = build_gan(dataset.shape[1:], latent_dim, filters=32,
                                          n_layers=2)
dataset_scaled = load_real_samples(scale=True)

train_gan(generator, discriminator, gan, dataset_scaled, latent_dim, n_epochs=20)

"""Observations:


*   The code produces images, but the images seem very noisy/random
*   Distinct dog features like eyes, nose and ears are not clearly visible. Instead there are a lot of random shapes and colors.

## Good parameter choices

These parameter choices were inspired by looking at existing GAN solutuions online such as:

1. [TF GAN tutorial](https://www.tensorflow.org/tutorials/generative/dcgan#create_the_models)

We observed that the tutorial used a large latent space and a large amounts of channels. However, the number of hidden layers is kept small because of the stride size.
"""

## Build and train the model (need around 10 epochs to start seeing some results)

latent_dim = 150 # 100
discriminator, generator, gan = build_gan(dataset.shape[1:], latent_dim, filters=350,
                                          n_layers=2) # 256 filters
dataset_scaled = load_real_samples(scale=True)

train_gan(generator, discriminator, gan, dataset_scaled, latent_dim, n_epochs=20)

"""Observation:


*   Distinct dog facial features like ears, nose, eyes are visible
*   Images are still noisy though

## GAN interpolation (Task 1.4)

I added 2 seed numbers for reproducible results. If you want 2 random samples each time you run this code, remove the random seed numbers
"""

# Create vector x and y
np.random.seed(102) # Remove seed if you want random runs each time
x = np.random.randn(1, latent_dim)
np.random.seed(103) # Remove seed if you want random runs each time
y = np.random.randn(1, latent_dim)

# Calculate the difference
diff = y - x

# Interpolation step
alphas = np.linspace(0, 1, 5)
data = np.zeros((5, latent_dim))

for idx in range(5):
    data[idx, :] = x + alphas[idx] * diff

# Upscaling step
generated_images = generator(data, training=False)
images = rescale_images(generated_images.numpy())

# Create a figure
plt.figure(figsize=(15, 3))  # Adjust the figure size to fit 5 images

# Subtitles
subtitles = ['x', 'x+0.25(y-x)', 'x+0.5(y-x)', 'x+0.75(y-x)', 'y']

# Plot
num_images = 5
for index in range(num_images):
    plt.subplot(1, num_images, 1 + index)  # 1 row, 5 columns
    plt.axis('off')
    plt.imshow(images[index])
    plt.title(subtitles[index], fontsize=12)

fig = plt.gcf()
fig.suptitle("Interpolation (5 steps from left to right) ", fontsize=14)

plt.show()