# -*- coding: utf-8 -*-
"""Assignment_2_Task_2-1_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17h8iGhYfECYtnB5MMuMJMfMEzYG9ya1O

<div style="text-align: right">   </div>


Introduction to Deep Learning (2024) &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;| &nbsp;
-------|-------------------
**Assignment 2 - Sequence processing using RNNs** | <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/UniversiteitLeidenLogo.svg/1280px-UniversiteitLeidenLogo.svg.png" width="300">



# Introduction


The goal of this assignment is to learn how to use encoder-decoder recurrent neural networks (RNNs). Specifically we will be dealing with a sequence to sequence problem and try to build recurrent models that can learn the principles behind simple arithmetic operations (**integer addition, subtraction and multiplication.**).

<img src="https://i.ibb.co/5Ky5pbk/Screenshot-2023-11-10-at-07-51-21.png" alt="Screenshot-2023-11-10-at-07-51-21" border="0" width="500"></a>

In this assignment you will be working with three different kinds of models, based on input/output data modalities:
1. **Text-to-text**: given a text query containing two integers and an operand between them (+ or -) the model's output should be a sequence of integers that match the actual arithmetic result of this operation
2. **Image-to-text**: same as above, except the query is specified as a sequence of images containing individual digits and an operand.
3. **Text-to-image**: the query is specified in text format as in the text-to-text model, however the model's output should be a sequence of images corresponding to the correct result.


### Description**
Let us suppose that we want to develop a neural network that learns how to add or subtract
two integers that are at most two digits long. For example, given input strings of 5 characters: ‘81+24’ or
’41-89’ that consist of 2 two-digit long integers and an operand between them, the network should return a
sequence of 3 characters: ‘105 ’ or ’-48 ’ that represent the result of their respective queries. Additionally,
we want to build a model that generalizes well - if the network can extract the underlying principles behind
the ’+’ and ’-’ operands and associated operations, it should not need too many training examples to generate
valid answers to unseen queries. To represent such queries we need 13 unique characters: 10 for digits (0-9),
2 for the ’+’ and ’-’ operands and one for whitespaces ’ ’ used as padding.
The example above describes a text-to-text sequence mapping scenario. However, we can also use different
modalities of data to represent our queries or answers. For that purpose, the MNIST handwritten digit
dataset is going to be used again, however in a slightly different format. The functions below will be used to create our datasets.

---

*To work on this notebook you should create a copy of it.*

# Function definitions for creating the datasets

First we need to create our datasets that are going to be used for training our models.

In order to create image queries of simple arithmetic operations such as '15+13' or '42-10' we need to create images of '+' and '-' signs using ***open-cv*** library. We will use these operand signs together with the MNIST dataset to represent the digits.
"""

import tensorflow as tf
import matplotlib.pyplot as plt
import cv2
import numpy as np
import tensorflow as tf
import random
from sklearn.model_selection import train_test_split
import pandas as pd
from tensorflow.keras.layers import Dense, RNN, LSTM, Flatten, TimeDistributed, LSTMCell
from tensorflow.keras.layers import RepeatVector, Conv2D, SimpleRNN, GRU, Reshape, ConvLSTM2D, Conv2DTranspose

from scipy.ndimage import rotate


# Create plus/minus operand signs
def generate_images(number_of_images=50, sign='-'):
    blank_images = np.zeros([number_of_images, 28, 28])  # Dimensionality matches the size of MNIST images (28x28)
    x = np.random.randint(12, 16, (number_of_images, 2)) # Randomized x coordinates
    y1 = np.random.randint(6, 10, number_of_images)       # Randomized y coordinates
    y2 = np.random.randint(18, 22, number_of_images)     # -||-

    for i in range(number_of_images): # Generate n different images
        cv2.line(blank_images[i], (y1[i], x[i,0]), (y2[i], x[i, 1]), (255,0,0), 2, cv2.LINE_AA)     # Draw lines with randomized coordinates
        if sign == '+':
            cv2.line(blank_images[i], (x[i,0], y1[i]), (x[i, 1], y2[i]), (255,0,0), 2, cv2.LINE_AA) # Draw lines with randomized coordinates
        if sign == '*':
            cv2.line(blank_images[i], (x[i,0], y1[i]), (x[i, 1], y2[i]), (255,0,0), 2, cv2.LINE_AA)
            # Rotate 45 degrees
            blank_images[i] = rotate(blank_images[i], -50, reshape=False)
            cv2.line(blank_images[i], (x[i,0], y1[i]), (x[i, 1], y2[i]), (255,0,0), 2, cv2.LINE_AA)
            blank_images[i] = rotate(blank_images[i], -50, reshape=False)
            cv2.line(blank_images[i], (x[i,0], y1[i]), (x[i, 1], y2[i]), (255,0,0), 2, cv2.LINE_AA)

    return blank_images

def show_generated(images, n=5):
    plt.figure(figsize=(2, 2))
    for i in range(n**2):
        plt.subplot(n, n, i+1)
        plt.axis('off')
        plt.imshow(images[i])
    plt.show()

show_generated(generate_images())
show_generated(generate_images(sign='+'))

def create_data(highest_integer, num_addends=2, operands=['+', '-']):
    """
    Creates the following data for all pairs of integers up to [1:highest integer][+/-][1:highest_integer]:

    @return:
    X_text: '51+21' -> text query of an arithmetic operation (5)
    X_img : Stack of MNIST images corresponding to the query (5 x 28 x 28) -> sequence of 5 images of size 28x28
    y_text: '72' -> answer of the arithmetic text query
    y_img :  Stack of MNIST images corresponding to the answer (3 x 28 x 28)

    Images for digits are picked randomly from the whole MNIST dataset.
    """

    num_indices = [np.where(MNIST_labels==x) for x in range(10)]
    num_data = [MNIST_data[inds] for inds in num_indices]
    image_mapping = dict(zip(unique_characters[:10], num_data))
    image_mapping['-'] = generate_images()
    image_mapping['+'] = generate_images(sign='+')
    image_mapping['*'] = generate_images(sign='*')
    image_mapping[' '] = np.zeros([1, 28, 28])

    X_text, X_img, y_text, y_img = [], [], [], []

    for i in range(highest_integer + 1):      # First addend
        for j in range(highest_integer + 1):  # Second addend
            for sign in operands: # Create all possible combinations of operands
                query_string = to_padded_chars(str(i) + sign + str(j), max_len=max_query_length, pad_right=True)
                query_image = []
                for n, char in enumerate(query_string):
                    image_set = image_mapping[char]
                    index = np.random.randint(0, len(image_set), 1)
                    query_image.append(image_set[index].squeeze())

                result = eval(query_string)
                result_string = to_padded_chars(result, max_len=max_answer_length, pad_right=True)
                result_image = []
                for n, char in enumerate(result_string):
                    image_set = image_mapping[char]
                    index = np.random.randint(0, len(image_set), 1)
                    result_image.append(image_set[index].squeeze())

                X_text.append(query_string)
                X_img.append(np.stack(query_image))
                y_text.append(result_string)
                y_img.append(np.stack(result_image))

    return np.stack(X_text), np.stack(X_img)/255., np.stack(y_text), np.stack(y_img)/255.

def to_padded_chars(integer, max_len=3, pad_right=False):
    """
    Returns a string of len()=max_len, containing the integer padded with ' ' on either right or left side
    """
    length = len(str(integer))
    padding = (max_len - length) * ' '
    if pad_right:
        return str(integer) + padding
    else:
        return padding + str(integer)

"""# Creating our data

The dataset consists of 20000 samples that (additions and subtractions between all 2-digit integers) and they have two kinds of inputs and label modalities:

  **X_text**: strings containing queries of length 5: ['  1+1  ', '11-18', ...]

  **X_image**: a stack of images representing a single query, dimensions: [5, 28, 28]

  **y_text**: strings containing answers of length 3: ['  2', '156']

  **y_image**: a stack of images that represents the answer to a query, dimensions: [3, 28, 28]
"""

# Illustrate the generated query/answer pairs

unique_characters = '0123456789+- '       # All unique characters that are used in the queries (13 in total: digits 0-9, 2 operands [+, -], and a space character ' '.)
highest_integer = 99                      # Highest value of integers contained in the queries

max_int_length = len(str(highest_integer))# Maximum number of characters in an integer
max_query_length = max_int_length * 2 + 1 # Maximum length of the query string (consists of two integers and an operand [e.g. '22+10'])
max_answer_length = 3    # Maximum length of the answer string (the longest resulting query string is ' 1-99'='-98')

# Create the data (might take around a minute)
(MNIST_data, MNIST_labels), _ = tf.keras.datasets.mnist.load_data()
X_text, X_img, y_text, y_img = create_data(highest_integer)
print(X_text.shape, X_img.shape, y_text.shape, y_img.shape)


## Display the samples that were created
def display_sample(n):
    labels = ['X_img:', 'y_img:']
    for i, data in enumerate([X_img, y_img]):
        plt.subplot(1,2,i+1)
        # plt.set_figheight(15)
        plt.axis('off')
        plt.title(labels[i])
        plt.imshow(np.hstack(data[n]), cmap='gray')
    print('='*50, f'\nQuery #{n}\n\nX_text: "{X_text[n]}" = y_text: "{y_text[n]}"')
    plt.show()

for _ in range(10):
    display_sample(np.random.randint(0, 10000, 1)[0])

"""## Helper functions

The functions below will help with input/output of the data.
"""

# One-hot encoding/decoding the text queries/answers so that they can be processed using RNNs
# You should use these functions to convert your strings and read out the output of your networks

def encode_labels(labels, max_len=3):
  n = len(labels)
  length = len(labels[0])
  char_map = dict(zip(unique_characters, range(len(unique_characters))))
  one_hot = np.zeros([n, length, len(unique_characters)])
  for i, label in enumerate(labels):
      m = np.zeros([length, len(unique_characters)])
      for j, char in enumerate(label):
          m[j, char_map[char]] = 1
      one_hot[i] = m

  return one_hot


def decode_labels(labels):
    pred = np.argmax(labels, axis=1)
    predicted = ''.join([unique_characters[i] for i in pred])

    return predicted

X_text_onehot = encode_labels(X_text)
y_text_onehot = encode_labels(y_text)

print(X_text_onehot.shape, y_text_onehot.shape)

from collections import defaultdict
labels_to_str = {1:"1 digit 1 digit addition no carry",2:"1 digit 2 digit addition no carry", 3:"2 digit 2 digit addition no carry",4:"1 digit 1 digit addition carry",
                 5:"1 digit 2 digit addition carry",6:"2 digit 2 digit addition carry",7:"1 digit 1 digit substraction no carry",8:"1 digit 2 digit substraction no carry",
                 9:"2 digit 2 digit substraction no carry",11:"1 digit 2 digit substraction carry",12:"2 digit 2 digit substraction carry",13:"Double carry addition",
                 14:"First digit carry addition"}
def classify_operations(X):

  count = 0
  op = 0
  num0 = 0
  num1 = 0
  classified_operations = defaultdict(int)
  for operation in X:
    carry = 0
    if '+' in operation:
      op = 0
      nums = operation.strip().split('+')
      if (int(nums[0])%10)+(int(nums[1])%10) >= 10:
        carry = 3
    else :
      op = 6
      nums = operation.strip().split('-')
      if (int(nums[0]))<(int(nums[1])):
        if (int(nums[1])%10)<(int(nums[0])%10):
          carry = 3
      else:
        if (int(nums[0])%10)<(int(nums[1])%10):
          carry = 3
    if len(nums[0])>1:
      num0 = 1
    else:
      num0 = 0
    if len(nums[1])>1:
      num1 = 2
    else:
      num1 = 1
    if (len(nums[0])>1 or len(nums[1])>1) and '+' in operation and carry == 3 and int(nums[0])+int(nums[1])>=100:
      classified_operations[labels_to_str[13]] += 1
    elif carry == 0 and '+' in operation and int(nums[0])+int(nums[1])>100:
      classified_operations[labels_to_str[14]] += 1
    else:
      classified_operations[labels_to_str[op+num0+num1+carry]] += 1
  return classified_operations

def show_mistakes_images(y_pred,y_text_test_onehot,X_img_test,num_mistakes_to_show):
  count = 0
  for pred,true,operation in zip(y_pred,y_text_test_onehot,X_img_test):
    if decode_labels(pred) != decode_labels(true):

      fig, ax = plt.subplots()
      ax.imshow(np.hstack(operation))
      plt.axis('off')
      plt.title(f'Predicted: {decode_labels(pred)} True:{decode_labels(true)}')
      plt.show()
      count +=1
      if count == num_mistakes_to_show:
        break

def count_mistakes(y_pred,y_text_test_onehot,X_text_test_onehot,op_test):
  mistakes = defaultdict(str)
  mistakes11noc = []
  for pred,true,operation in zip(y_pred,y_text_test_onehot,X_text_test_onehot):
    if decode_labels(pred) != decode_labels(true):
      mistakes[decode_labels(operation)] += decode_labels(pred)
  print(f'Number of mistakes: {len(mistakes)}/{len(y_text_test_onehot)}')
  classified_mistakes = classify_operations(mistakes.keys())

  for op in labels_to_str.values():
    print(f'{op}:{classified_mistakes[op]}/{op_test[op]}')
  return classified_mistakes

def plot_multiple_splits_histogram(splits,distribution_type,set_type):
    split_names = list(splits.keys())
    operation_types = list(next(iter(splits.values())).keys())

    x = np.arange(len(operation_types))
    bar_width = 0.2
    colors = plt.cm.tab10.colors[:len(split_names)]

    plt.figure(figsize=(10, 6))
    for i, split_name in enumerate(split_names):
        counts = [splits[split_name][op] for op in operation_types]
        plt.bar(x + i * bar_width, counts, bar_width, label=split_name, color=colors[i], edgecolor="black")

    plt.xlabel("Operation Types")
    plt.ylabel("Number of Operations")
    plt.title(f"Distribution of {set_type} {distribution_type} Across Splits")
    plt.xticks(x + bar_width * (len(split_names) - 1) / 2, operation_types, rotation=45, ha='right')
    plt.legend(title="Splits")
    plt.tight_layout()
    plt.show()

import seaborn as sns

def plot_distribution_heatmap(splits):

    df = pd.DataFrame(splits).T

    plt.figure(figsize=(10, 6))
    sns.heatmap(df, annot=True, fmt="d", cmap="YlGnBu", cbar=True, linewidths=0.5)
    plt.xticks(rotation=45, ha='right')

    plt.xlabel("Operation Types")
    plt.ylabel("Splits")
    plt.title("Operation type count across train-test splits")
    plt.tight_layout()

    plt.show()

def plot_mistake_percentage_heatmap(total_operations, mistakes):

    percentages = {}
    for split, operations in total_operations.items():
        percentages[split] = {
            op: (mistakes[split][op] / operations[op] * 100 if operations[op] > 0 else 0)
            for op in operations
        }

    df_percentages = pd.DataFrame(percentages).T

    plt.figure(figsize=(10, 6))
    sns.heatmap(df_percentages, annot=True, fmt=".2f", cmap="Reds", cbar=True, linewidths=0.5)
    plt.xticks(rotation=45, ha='right')

    plt.xlabel("Operation Types")
    plt.ylabel("Splits")
    plt.title("Error proportion (%) per operation type over train-test split")
    plt.tight_layout()

    plt.show()

def plot_single_split(split_name, split_data):

    operation_types = list(split_data.keys())
    counts = list(split_data.values())

    plt.figure(figsize=(8, 5))
    plt.bar(operation_types, counts, edgecolor="black")
    plt.xlabel("Operation Types")
    plt.ylabel("Number of Operations")
    plt.title(f"Distribution of Operation Types in {split_name}")
    plt.xticks(rotation=45, ha='right')
    for i, count in enumerate(counts):
        plt.text(i, count + 0.5, str(count), ha='center', va='bottom', fontsize=9)

    plt.show()

classify_operations(X_text)

"""---
---

## I. Text-to-text RNN model

The following code showcases how Recurrent Neural Networks (RNNs) are built using Keras. Several new layers are going to be used:

1. LSTM
2. TimeDistributed
3. RepeatVector

The code cell below explains each of these new components.

<img src="https://i.ibb.co/NY7FFTc/Screenshot-2023-11-10-at-09-27-25.png" alt="Screenshot-2023-11-10-at-09-27-25" border="0" width="500"></a>

"""

def build_text2text_model():

    # We start by initializing a sequential model
    text2text = tf.keras.Sequential()

    # "Encode" the input sequence using an RNN, producing an output of size 256.
    # In this case the size of our input vectors is [5, 13] as we have queries of length 5 and 13 unique characters. Each of these 5 elements in the query will be fed to the network one by one,
    # as shown in the image above (except with 5 elements).
    # Hint: In other applications, where your input sequences have a variable length (e.g. sentences), you would use input_shape=(None, unique_characters).
    text2text.add(LSTM(256, input_shape=(None, len(unique_characters))))

    # As the decoder RNN's input, repeatedly provide with the last output of RNN for each time step. Repeat 3 times as that's the maximum length of the output (e.g. '  1-99' = '-98')
    # when using 2-digit integers in queries. In other words, the RNN will always produce 3 characters as its output.
    text2text.add(RepeatVector(max_answer_length))

    # By setting return_sequences to True, return not only the last output but all the outputs so far in the form of (num_samples, timesteps, output_dim). This is necessary as TimeDistributed in the below expects
    # the first dimension to be the timesteps.
    text2text.add(LSTM(256, return_sequences=True))

    # Apply a dense layer to the every temporal slice of an input. For each of step of the output sequence, decide which character should be chosen.
    text2text.add(TimeDistributed(Dense(len(unique_characters), activation='softmax')))

    # Next we compile the model using categorical crossentropy as our loss function.
    text2text.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    text2text.summary()

    return text2text

train_splits = {}
test_splits = {}
mistakes_splits = {}
op_total_splits = {}

"""90% test split"""

X_text_train, X_text_test, y_text_train, y_text_test = train_test_split(X_text, y_text,test_size=0.9, random_state=42, shuffle=True)

X_text_train_onehot90 = encode_labels(X_text_train)
y_text_train_onehot90 = encode_labels(y_text_train)
X_text_test_onehot90 = encode_labels(X_text_test)
y_text_test_onehot90 = encode_labels(y_text_test)

train_ops90 = classify_operations(X_text_train)
test_ops90 = classify_operations(X_text_test)
train_splits['10 train'] = train_ops90
test_splits['10 train'] = test_ops90

print(f'Operation type distribution on train set:')
for k,v in train_ops90.items():
  print(f'{k} {v}/{len(X_text_train)}')

model90 = build_text2text_model()
try:
  history90 = model90.fit(X_text_train_onehot90, y_text_train_onehot90,
                        epochs=10,
                        batch_size=8)
except KeyboardInterrupt:
    print("\nTraining Stopped")

model90.evaluate(X_text_test_onehot90, y_text_test_onehot90)

y_pred90 = model90.predict(X_text_test_onehot90)

y_pred90.shape

mistakes90 = count_mistakes(y_pred90,y_text_test_onehot90,X_text_test_onehot90,test_ops90)
mistakes_splits['10 train'] = mistakes90

# Plot accuracy
plt.figure(figsize=(10,3))
plt.plot(history90.history['accuracy'])
plt.title('Model Accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['Train'], loc='upper left')
plt.show()

"""50% test split"""

from sklearn.model_selection import train_test_split
X_text_train, X_text_test, y_text_train, y_text_test = train_test_split(X_text, y_text,test_size=0.5, random_state=42, shuffle=True)

X_text_train_onehot50 = encode_labels(X_text_train)
y_text_train_onehot50 = encode_labels(y_text_train)
X_text_test_onehot50 = encode_labels(X_text_test)
y_text_test_onehot50 = encode_labels(y_text_test)

train_ops50 = classify_operations(X_text_train)
test_ops50 = classify_operations(X_text_test)
train_splits['50 train'] = train_ops50
test_splits['50 train'] = test_ops50

print(f'Operation type distribution on train set:')
for k,v in train_ops50.items():
  print(f'{k} {v}/{len(X_text_train)}')

model50 = build_text2text_model()
try:
  history50 = model50.fit(X_text_train_onehot50, y_text_train_onehot50,
                        epochs=10,
                        batch_size=8)
except KeyboardInterrupt:
    print("\nTraining Stopped")

model50.evaluate(X_text_test_onehot50, y_text_test_onehot50)

# Plot accuracy
plt.figure(figsize=(10,3))
plt.plot(history50.history['accuracy'])
plt.title('Model Accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['Train', 'Val'], loc='upper left')
plt.show()

y_pred50=model50.predict(X_text_test_onehot50)

y_pred50.shape

mistakes50 = count_mistakes(y_pred50,y_text_test_onehot50,X_text_test_onehot50,test_ops50)
mistakes_splits['50 train'] = mistakes50

"""25% test split"""

X_text_train, X_text_test, y_text_train, y_text_test = train_test_split(X_text, y_text,test_size=0.25, random_state=42, shuffle=True)

X_text_train_onehot25 = encode_labels(X_text_train)
y_text_train_onehot25 = encode_labels(y_text_train)
X_text_test_onehot25 = encode_labels(X_text_test)
y_text_test_onehot25 = encode_labels(y_text_test)

train_ops25 = classify_operations(X_text_train)
test_ops25 = classify_operations(X_text_test)
train_splits['75 train'] = train_ops25
test_splits['75 train'] = test_ops25

print(f'Operation type distribution on train set:')
for k,v in train_ops25.items():
  print(f'{k} {v}/{len(X_text_train)}')

model25 = build_text2text_model()
try:
  history25 = model25.fit(X_text_train_onehot25, y_text_train_onehot25,
                        epochs=10,
                        batch_size=8)
except KeyboardInterrupt:
    print("\nTraining Stopped")

model25.evaluate(X_text_test_onehot25, y_text_test_onehot25)

# Plot accuracy
plt.figure(figsize=(10,3))
plt.plot(history25.history['accuracy'])
plt.title('Model Accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['Train'], loc='upper left')
plt.show()

y_pred25 = model25.predict(X_text_test_onehot25)

y_pred25.shape

mistakes25 = count_mistakes(y_pred25,y_text_test_onehot25,X_text_test_onehot25,test_ops25)
mistakes_splits['75 train'] = mistakes25

"""10% test split"""

X_text_train, X_text_test, y_text_train, y_text_test = train_test_split(X_text, y_text,test_size=0.1, random_state=42, shuffle=True)

X_text_train_onehot10 = encode_labels(X_text_train)
y_text_train_onehot10 = encode_labels(y_text_train)
X_text_test_onehot10 = encode_labels(X_text_test)
y_text_test_onehot10 = encode_labels(y_text_test)

train_ops10 = classify_operations(X_text_train)
test_ops10 = classify_operations(X_text_test)
train_splits['90 train'] = train_ops10
test_splits['90 train'] = test_ops10

print(f'Operation type distribution on train set:')
for k,v in train_ops10.items():
  print(f'{k} {v}/{len(X_text_train)}')

plot_multiple_splits_histogram(train_splits,'Operation Types',"Training Set")

plot_multiple_splits_histogram(test_splits,'Operation Types',"Test Set")

model10 = build_text2text_model()
try:
  history10 = model10.fit(X_text_train_onehot10, y_text_train_onehot10,
                        epochs=10,
                        batch_size=8)
except KeyboardInterrupt:
    print("\nTraining Stopped")

model10.evaluate(X_text_test_onehot10, y_text_test_onehot10)

# Plot accuracy
plt.figure(figsize=(10,3))
plt.plot(history10.history['accuracy'])
plt.title('Model Accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['Train', 'Val'], loc='upper left')
plt.show()

y_pred10 = model10.predict(X_text_test_onehot10)

y_pred10.shape

mistakes10 = count_mistakes(y_pred10,y_text_test_onehot10,X_text_test_onehot10,test_ops10)
mistakes_splits['90 train'] = mistakes10

histories = [history90,history50,history25,history10]
# Plot accuracy
plt.figure(figsize=(10,3))
for h in histories:
  plt.plot(h.history['accuracy'])
plt.title('Train Splits Model Accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['10 split', '50 split','75 split','90 splot'], loc='upper left')

plt.savefig('splits_accuracy.png')

plt.show()

plot_multiple_splits_histogram(mistakes_splits,'Mistakes',"")

for k,v in test_splits.items():
  print(f'key:{k}value:{v}')

plot_mistake_percentage_heatmap(test_splits, mistakes_splits)

plot_distribution_heatmap(train_splits)



"""
---
---

## II. Image to text RNN Model

Hint: There are two ways of building the encoder for such a model - again by using the regular LSTM cells (with flattened images as input vectors) or recurrect convolutional layers [ConvLSTM2D](https://keras.io/api/layers/recurrent_layers/conv_lstm2d/).

The goal here is to use **X_img** as inputs and **y_text** as outputs."""

indices = np.arange(len(X_text))

X_indices_train, X_indices_test, y_text_train, y_text_test = train_test_split(indices, y_text,test_size=0.1, random_state=42, shuffle=True)
X_itt_train_90 = np.array([X_img[i] for i in X_indices_train])
X_itt_test_90 = np.array([X_img[i] for i in X_indices_test])
X_text_train = np.array([X_text[i] for i in X_indices_train])
X_text_test = np.array([X_text[i] for i in X_indices_test])

X_text_test_onehot = encode_labels(X_text_test)
y_itt_train_90 = encode_labels(y_text_train)
y_itt_test_90 = encode_labels(y_text_test)

## Your code
from keras.layers import GlobalAveragePooling2D
def build_imgtotext_convoltsm():
    itt = tf.keras.Sequential()
    itt.add(ConvLSTM2D(filters=64, kernel_size=(3, 3), return_sequences=False, input_shape=( 5, 28, 28, 1)))
    itt.add(GlobalAveragePooling2D())
    itt.add(Flatten())
    itt.add(RepeatVector(3))
    itt.add(LSTM(256, return_sequences=True))
    itt.add(TimeDistributed(Dense(13, activation='softmax')))
    itt.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    itt.summary()

    return itt

def build_imgtotext_lstm():
    itt = tf.keras.Sequential()
    itt.add(TimeDistributed(Flatten(), input_shape=(5, 28, 28, 1)))
    itt.add(LSTM(256, return_sequences=False))
    itt.add(RepeatVector(3))
    itt.add(LSTM(256, return_sequences=True))
    itt.add(TimeDistributed(Dense(13, activation='softmax')))
    itt.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    itt.summary()

    return itt

def build_imgtotext_convoltsm_multilayer():
    itt = tf.keras.Sequential()
    itt.add(ConvLSTM2D(filters=64, kernel_size=(3, 3), return_sequences=True, input_shape=( 5, 28, 28, 1)))
    itt.add(ConvLSTM2D(filters=32, kernel_size=(3, 3), return_sequences=False))
    itt.add(GlobalAveragePooling2D())
    itt.add(Flatten())
    itt.add(RepeatVector(3))
    itt.add(LSTM(256, return_sequences=True))
    itt.add(LSTM(312, return_sequences=True))
    itt.add(TimeDistributed(Dense(13, activation='softmax')))
    itt.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    itt.summary()

    return itt

def build_imgtotext_lstm_multylayer():
    itt = tf.keras.Sequential()
    itt.add(TimeDistributed(Flatten(), input_shape=(5, 28, 28, 1)))
    itt.add(LSTM(256, return_sequences=True))
    itt.add(LSTM(312, return_sequences=False))
    itt.add(RepeatVector(3))
    itt.add(LSTM(312, return_sequences=True))
    itt.add(LSTM(256, return_sequences=True))
    itt.add(TimeDistributed(Dense(13, activation='softmax')))
    itt.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    itt.summary()

    return itt

imagetotext_convoltsm=build_imgtotext_convoltsm()
imagetotext_ltsm=build_imgtotext_lstm()

imagetotext_convoltsm_multilayer=build_imgtotext_convoltsm_multilayer()
imagetotext_ltsm_multilayer=build_imgtotext_lstm_multylayer()

imagetotext_convoltsm.fit(X_itt_train_90, y_itt_train_90, batch_size=64, epochs=30)
imagetotext_ltsm.fit(X_itt_train_90, y_itt_train_90, batch_size=64, epochs=30)
imagetotext_convoltsm_multilayer.fit(X_itt_train_90, y_itt_train_90, batch_size=64, epochs=30)
imagetotext_ltsm_multilayer.fit(X_itt_train_90, y_itt_train_90, batch_size=64, epochs=30)

imagetotext_convoltsm.evaluate(X_itt_test_90,y_itt_test_90)

imagetotext_ltsm.evaluate(X_itt_test_90,y_itt_test_90)

imagetotext_convoltsm_multilayer.evaluate(X_itt_test_90,y_itt_test_90)

imagetotext_ltsm_multilayer.evaluate(X_itt_test_90,y_itt_test_90)

y_pred_convolltsm = imagetotext_convoltsm.predict(X_itt_test_90)
y_pred_lstm = imagetotext_ltsm.predict(X_itt_test_90)
y_pred_convolstm_multilayer = imagetotext_convoltsm_multilayer.predict(X_itt_test_90)
y_pred_lstm_multilayer = imagetotext_ltsm_multilayer.predict(X_itt_test_90)

mistakes_splits_itt={}

train_ops = classify_operations(X_text_train)
test_ops = classify_operations(X_text_test)
print(f'Operation type distribution on train set:')
for k,v in train_ops.items():
  print(f'{k} {v}/{len(X_text_train)}')

mistakes_convollstm = count_mistakes(y_pred_convolltsm,y_itt_test_90,X_text_test_onehot,test_ops)

mistakes_splits_itt['convlstm'] = mistakes_convollstm

mistakes_lstm = count_mistakes(y_pred_lstm,y_itt_test_90,X_text_test_onehot,test_ops)
mistakes_splits_itt['lstm'] = mistakes_lstm

mistakes_multiconvollstm = count_mistakes(y_pred_convolstm_multilayer,y_itt_test_90,X_text_test_onehot,test_ops)

mistakes_splits_itt['convlstmmulti'] = mistakes_convollstm

mistakes_lstmmulti = count_mistakes(y_pred_lstm_multilayer,y_itt_test_90,X_text_test_onehot,test_ops)
mistakes_splits_itt['lstmmulti'] = mistakes_lstmmulti

plot_multiple_architectures_histogram(mistakes_splits_itt)