# -*- coding: utf-8 -*-
"""Assignment_2_Task_2.2_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YW9uq4Pm8e_a11kupHhiB0-CH_iYiBR-
"""

import tensorflow as tf
import matplotlib.pyplot as plt
import cv2
import numpy as np
import tensorflow as tf
import random
from sklearn.model_selection import train_test_split
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
from tensorflow.keras.layers import Dense, RNN, LSTM, Flatten, TimeDistributed, LSTMCell
from tensorflow.keras.layers import RepeatVector, Conv2D, SimpleRNN, GRU, Reshape, ConvLSTM2D, Conv2DTranspose

from scipy.ndimage import rotate


# Create plus/minus operand signs
def generate_images(number_of_images=50, sign='-'):
    blank_images = np.zeros([number_of_images, 28, 28])  # Dimensionality matches the size of MNIST images (28x28)
    x = np.random.randint(12, 16, (number_of_images, 2)) # Randomized x coordinates
    y1 = np.random.randint(6, 10, number_of_images)       # Randomized y coordinates
    y2 = np.random.randint(18, 22, number_of_images)     # -||-

    for i in range(number_of_images): # Generate n different images
        cv2.line(blank_images[i], (y1[i], x[i,0]), (y2[i], x[i, 1]), (255,0,0), 2, cv2.LINE_AA)     # Draw lines with randomized coordinates
        if sign == '+':
            cv2.line(blank_images[i], (x[i,0], y1[i]), (x[i, 1], y2[i]), (255,0,0), 2, cv2.LINE_AA) # Draw lines with randomized coordinates
        if sign == '*':
            cv2.line(blank_images[i], (x[i,0], y1[i]), (x[i, 1], y2[i]), (255,0,0), 2, cv2.LINE_AA)
            # Rotate 45 degrees
            blank_images[i] = rotate(blank_images[i], -50, reshape=False)
            cv2.line(blank_images[i], (x[i,0], y1[i]), (x[i, 1], y2[i]), (255,0,0), 2, cv2.LINE_AA)
            blank_images[i] = rotate(blank_images[i], -50, reshape=False)
            cv2.line(blank_images[i], (x[i,0], y1[i]), (x[i, 1], y2[i]), (255,0,0), 2, cv2.LINE_AA)

    return blank_images

def show_generated(images, n=5):
    plt.figure(figsize=(2, 2))
    for i in range(n**2):
        plt.subplot(n, n, i+1)
        plt.axis('off')
        plt.imshow(images[i])
    plt.show()

show_generated(generate_images())
show_generated(generate_images(sign='+'))

def create_data(highest_integer, num_addends=2, operands=['+', '-']):
    """
    Creates the following data for all pairs of integers up to [1:highest integer][+/-][1:highest_integer]:

    @return:
    X_text: '51+21' -> text query of an arithmetic operation (5)
    X_img : Stack of MNIST images corresponding to the query (5 x 28 x 28) -> sequence of 5 images of size 28x28
    y_text: '72' -> answer of the arithmetic text query
    y_img :  Stack of MNIST images corresponding to the answer (3 x 28 x 28)

    Images for digits are picked randomly from the whole MNIST dataset.
    """

    num_indices = [np.where(MNIST_labels==x) for x in range(10)]
    num_data = [MNIST_data[inds] for inds in num_indices]
    image_mapping = dict(zip(unique_characters[:10], num_data))
    image_mapping['-'] = generate_images()
    image_mapping['+'] = generate_images(sign='+')
    image_mapping['*'] = generate_images(sign='*')
    image_mapping[' '] = np.zeros([1, 28, 28])

    X_text, X_img, y_text, y_img = [], [], [], []

    for i in range(highest_integer + 1):      # First addend
        for j in range(highest_integer + 1):  # Second addend
            for sign in operands: # Create all possible combinations of operands
                query_string = to_padded_chars(str(i) + sign + str(j), max_len=max_query_length, pad_right=True)
                query_image = []
                for n, char in enumerate(query_string):
                    image_set = image_mapping[char]
                    index = np.random.randint(0, len(image_set), 1)
                    query_image.append(image_set[index].squeeze())

                result = eval(query_string)
                result_string = to_padded_chars(result, max_len=max_answer_length, pad_right=True)
                result_image = []
                for n, char in enumerate(result_string):
                    image_set = image_mapping[char]
                    index = np.random.randint(0, len(image_set), 1)
                    result_image.append(image_set[index].squeeze())

                X_text.append(query_string)
                X_img.append(np.stack(query_image))
                y_text.append(result_string)
                y_img.append(np.stack(result_image))

    return np.stack(X_text), np.stack(X_img)/255., np.stack(y_text), np.stack(y_img)/255.

def to_padded_chars(integer, max_len=3, pad_right=False):
    """
    Returns a string of len()=max_len, containing the integer padded with ' ' on either right or left side
    """
    length = len(str(integer))
    padding = (max_len - length) * ' '
    if pad_right:
        return str(integer) + padding
    else:
        return padding + str(integer)

# Illustrate the generated query/answer pairs

unique_characters = '0123456789+- '       # All unique characters that are used in the queries (13 in total: digits 0-9, 2 operands [+, -], and a space character ' '.)
highest_integer = 99                      # Highest value of integers contained in the queries

max_int_length = len(str(highest_integer))# Maximum number of characters in an integer
max_query_length = max_int_length * 2 + 1 # Maximum length of the query string (consists of two integers and an operand [e.g. '22+10'])
max_answer_length = 3    # Maximum length of the answer string (the longest resulting query string is ' 1-99'='-98')

# Create the data (might take around a minute)
(MNIST_data, MNIST_labels), _ = tf.keras.datasets.mnist.load_data()
X_text, X_img, y_text, y_img = create_data(highest_integer)
print(X_text.shape, X_img.shape, y_text.shape, y_img.shape)


## Display the samples that were created
def display_sample(n):
    labels = ['X_img:', 'y_img:']
    for i, data in enumerate([X_img, y_img]):
        plt.subplot(1,2,i+1)
        # plt.set_figheight(15)
        plt.axis('off')
        plt.title(labels[i])
        plt.imshow(np.hstack(data[n]), cmap='gray')
    print('='*50, f'\nQuery #{n}\n\nX_text: "{X_text[n]}" = y_text: "{y_text[n]}"')
    plt.show()

for _ in range(10):
    display_sample(np.random.randint(0, 10000, 1)[0])

# One-hot encoding/decoding the text queries/answers so that they can be processed using RNNs
# You should use these functions to convert your strings and read out the output of your networks

def encode_labels(labels, max_len=3):
  n = len(labels)
  length = len(labels[0])
  char_map = dict(zip(unique_characters, range(len(unique_characters))))
  one_hot = np.zeros([n, length, len(unique_characters)])
  for i, label in enumerate(labels):
      m = np.zeros([length, len(unique_characters)])
      for j, char in enumerate(label):
          m[j, char_map[char]] = 1
      one_hot[i] = m

  return one_hot


def decode_labels(labels):
    pred = np.argmax(labels, axis=1)
    predicted = ''.join([unique_characters[i] for i in pred])

    return predicted

X_text_onehot = encode_labels(X_text)
y_text_onehot = encode_labels(y_text)

print(X_text_onehot.shape, y_text_onehot.shape)

#######################added functions################

from sklearn.model_selection import train_test_split
from tensorflow.keras.callbacks import Callback
import matplotlib.pyplot as plt


def split_xy(x, y, train_split):
    """
    Splits x and y into training and test sets based on the train split ratio using train_test_split.

    Parameters:
        x (np.ndarray): Input features.
        y (np.ndarray): Target values.
        train_split (float): Proportion of data to be used for training (e.g., 0.9 for 90%).

    Returns:
        tuple: x_train, x_test, y_train, y_test
    """
    if not 0 < train_split < 1:
        raise ValueError("train_split must be a float between 0 and 1 (exclusive).")

    x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=train_split, random_state=None, shuffle=True)
    return x_train, x_test, y_train, y_test

def augment_data(X, y, multiplier):
    """
    Augments the dataset by replicating it based on the multiplier.

    Parameters:
        X (numpy array): Input data (e.g., one-hot encoded equations).
        y (numpy array): Target data (e.g., sequence of images).
        multiplier (int): The factor by which to enlarge the dataset.

    Returns:
        X_augmented (numpy array): Augmented input data.
        y_augmented (numpy array): Augmented target data.
    """
    # Check if multiplier is an integer
    if not isinstance(multiplier, int) or multiplier <= 0:
        raise ValueError("Multiplier must be a positive integer.")

    # Replicating the dataset
    X_augmented = np.tile(X, (multiplier, 1, 1))  # Replicate the data
    y_augmented = np.tile(y, (multiplier, 1, 1, 1))  # Replicate the target sequence of images

    return X_augmented, y_augmented



class EpochEndPredictor(Callback):
    def __init__(self, sample_indices, x_train, y_train, decode_labels):
        """
        Custom callback to make the model predict on specific training samples after each epoch.

        Args:
            sample_indices (list of int): Indices of the samples in the training data.
            x_train (np.ndarray): Training data.
            y_train (np.ndarray): Ground truth labels for the training data.
            decode_labels (function): Function to decode the label (e.g., text query).
        """
        super(EpochEndPredictor, self).__init__()
        self.sample_indices = sample_indices
        self.x_samples = x_train[sample_indices]  # Extract the specific samples
        self.y_samples = y_train[sample_indices]
        self.decode_labels = decode_labels  # Store the decode function

    def on_epoch_end(self, epoch, logs=None):
        print(f"\nEpoch {epoch + 1} predictions:")

        # Create a figure to plot 3 images (3 columns for each sample)
        plt.figure(figsize=(12, 4))

        for i, (x_sample, y_sample) in enumerate(zip(self.x_samples, self.y_samples)):
            # Predict on the sample (reshape if necessary)
            x_sample = x_sample[np.newaxis, :]  # Add batch dimension to shape (1, 5, 13) if needed
            prediction = self.model.predict(x_sample, verbose=0)  # Prediction shape (1, 5, 28, 28)

            # Decode the text query for the current sample
            decoded_query = self.decode_labels(self.x_samples[i])  # Use decode_labels function

            # Plot the predictions for each time step (sequence of 3 images)
            for t in range(3):  # Plot the first 3 time steps
                plt.subplot(1, 3, t + 1)  # Create subplots for 3 images
                plt.imshow(prediction[0][t], cmap='gray')  # Plot the 28x28 image for time step t
                plt.axis('off')  # Hide the axes
                plt.title(f"{decoded_query}")  # Print the decoded text query on the title

        plt.tight_layout()
        plt.show()

def plot_prediction(test,pred,num):

    for i in range(num):
        decoded_input = decode_labels(test[i])
        predicted_images = pred[i]  # This should have shape (3, 28, 28, 1)

        print(f"Shape of predicted_images: {predicted_images.shape}")
        fig, axs = plt.subplots(1, 3, figsize=(15, 5))
        for j in range(3):
            axs[j].imshow(predicted_images[j].reshape(28, 28), cmap='gray')
            axs[j].axis('off')

        plt.suptitle(f"Input: {decoded_input}")
        plt.show()

def plot_prediction_separate(test,pred,num):
    for i in range(num):
        decoded_input = decode_labels(test[i])
        predicted_images = pred[:, i, :, :, 0]  # Select the 3 digits for the i-th sample (shape: 3, 28, 28)
        fig, axs = plt.subplots(1, 3, figsize=(15, 5))
        for j in range(3):
            axs[j].imshow(predicted_images[j].reshape(28, 28), cmap='gray')
            axs[j].axis('off')
        plt.suptitle(f"Input: {decoded_input}")
        plt.show()

"""<h1>Models</h1>"""

from tensorflow.keras.layers import Input
from tensorflow.keras.models import Model

def texttoimage_deconvo():
    tti= tf.keras.Sequential()
    tti.add(LSTM(512, return_sequences=True,input_shape=(None, len(unique_characters))))
    tti.add(LSTM(196, return_sequences=True,input_shape=(None,512)))
    tti.add(LSTM(196, return_sequences=False,input_shape=(None,512)))
    tti.add(RepeatVector(3))
    tti.add(TimeDistributed(Reshape((14, 14, 1), input_shape=(194,))))
    tti.add(TimeDistributed(Conv2DTranspose(filters=64, kernel_size=(3, 3), strides=(2, 2), padding='same', activation='sigmoid'))) #3x28x28x64
    tti.add(TimeDistributed(Conv2DTranspose(filters=32, kernel_size=(3, 3), strides=(1, 1), padding='same', activation='sigmoid'))) #3x28x28x32
    tti.add(TimeDistributed(Conv2DTranspose(filters=1, kernel_size=(3, 3), strides=(1, 1), padding='same', activation='sigmoid'))) #3x28x28x1
    tti.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    tti.summary()
    return tti

def texttoimage_separate():
    input_layer = Input(shape=(None, len(unique_characters)))
    x = LSTM(512, return_sequences=True)(input_layer)
    x = LSTM(784, return_sequences=False)(x)

    # Digit 1 branch
    digit_1 = Dense(784,activation='relu')(x)
    digit_1 = Reshape((28, 28, 1))(digit_1)
    digit_1 = Conv2DTranspose(128, (3, 3), strides=(1, 1), padding='same', activation='relu')(digit_1)
    digit_1 = Conv2DTranspose(64, (3, 3), strides=(1, 1), padding='same', activation='relu')(digit_1)
    digit_1 = Conv2DTranspose(64, (3, 3), strides=(1, 1), padding='same', activation='relu')(digit_1)
    digit_1 = Conv2DTranspose(1, (3, 3), padding='same', activation='sigmoid')(digit_1)

    # Digit 2 branch
    digit_2 = Dense(784,activation='relu')(x)
    digit_2 = Reshape((28, 28, 1))(digit_2)
    digit_2 = Conv2DTranspose(128, (3, 3), strides=(1, 1), padding='same', activation='relu')(digit_2)
    digit_2 = Conv2DTranspose(64, (3, 3), strides=(1, 1), padding='same', activation='relu')(digit_2)
    digit_2 = Conv2DTranspose(64, (3, 3), strides=(1, 1), padding='same', activation='relu')(digit_2)
    digit_2 = Conv2DTranspose(1, (3, 3), padding='same', activation='sigmoid')(digit_2)

    # Digit 3 branch
    digit_3 = Dense(784,activation='relu')(x)
    digit_3 = Reshape((28, 28, 1))(digit_3)
    digit_3 = Conv2DTranspose(128, (3, 3), strides=(1, 1), padding='same', activation='relu')(digit_3)
    digit_3 = Conv2DTranspose(64, (3, 3), strides=(1, 1), padding='same', activation='relu')(digit_3)
    digit_3 = Conv2DTranspose(64, (3, 3), strides=(1, 1), padding='same', activation='relu')(digit_3)
    digit_3 = Conv2DTranspose(1, (3, 3), padding='same', activation='sigmoid')(digit_3)

    # Model compilation
    model = Model(inputs=input_layer, outputs=[digit_1, digit_2, digit_3])
    model.compile(
    loss=['binary_crossentropy', 'binary_crossentropy', 'binary_crossentropy'],  # One loss per output
    optimizer='adam',
    metrics=[['accuracy'], ['accuracy'], ['accuracy']]  # One metric list per output
    )
    model.summary()
    return model

def texttoimage_vector():
    tti= tf.keras.Sequential()
    tti.add(LSTM(124, return_sequences=True, input_shape=(None, len(unique_characters))))
    tti.add(LSTM(196, return_sequences=True,))
    tti.add(LSTM(392, return_sequences=False,))
    tti.add(RepeatVector(3))
    tti.add(LSTM(392, return_sequences=True,))
    tti.add(LSTM(392, return_sequences=True,))
    tti.add(LSTM(784, return_sequences=True,))
    tti.add(TimeDistributed(Dense(1568,activation='tanh')))
    tti.add(TimeDistributed(Dense(784,activation='sigmoid')))
    tti.add(TimeDistributed(Reshape((28, 28, 1), input_shape=(784,))))
    tti.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    tti.summary()
    return tti

def texttoimage_decode_encode_deconvolutional():
    tti= tf.keras.Sequential()
    tti.add(LSTM(512, return_sequences=True, input_shape=(None, len(unique_characters))))
    tti.add(LSTM(784, return_sequences=False,))
    tti.add(RepeatVector(3))
    tti.add(TimeDistributed(Reshape((28, 28, 1), input_shape=(784,))))
    tti.add(TimeDistributed(Conv2DTranspose(filters=1, kernel_size=(3, 3), strides=(1, 1), padding='same', activation='sigmoid'))) #3x28x28x1
    tti.add(ConvLSTM2D(filters=1, kernel_size=(3, 3), strides=(1, 1), return_sequences=True, padding='same'))
    tti.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    tti.summary()
    return tti

def texttoimage_convolstm():
    tti= tf.keras.Sequential()
    tti.add(LSTM(784, return_sequences=False, input_shape=(None, len(unique_characters))))
    tti.add(RepeatVector(3))
    tti.add(TimeDistributed(Reshape((28, 28, 1))))
    tti.add(ConvLSTM2D(filters=64, kernel_size=(3, 3), strides=(1, 1), return_sequences=True, padding='same'))
    tti.add(ConvLSTM2D(filters=32, kernel_size=(3, 3), strides=(1, 1), return_sequences=True, padding='same'))
    #tti.add(TimeDistributed(Flatten()))
    #tti.add(TimeDistributed(Dense(784, activation='sigmoid')))
    #tti.add(TimeDistributed(Reshape((28, 28))))
    #tti.add(TimeDistributed(Conv2DTranspose(filters=1, kernel_size=(3, 3), strides=(1, 1), padding='same', activation='sigmoid')))
    tti.add(ConvLSTM2D(filters=1, kernel_size=(3, 3), strides=(1, 1), return_sequences=True, padding='same'))
    tti.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    tti.summary()
    return tti

# 2 part model separated text encoding part and image decoder part
def two_part_text_to_image(t2t):
    # Extract the first LSTM layer (encoder part)
    encoder_layer = t2t.layers[0]

    # Freeze the encoder's first LSTM layer
    encoder_layer.trainable = False

    # Define the new text-to-image model
    tti = tf.keras.Sequential()

    # Add the pre-trained encoder (only the first LSTM layer) to the new model
    tti.add(encoder_layer)

    # Add RepeatVector to repeat the vector 3 times to create a sequence
    tti.add(RepeatVector(3))

    # Add TimeDistributed Dense layer for latent space projection (to output 784, which represents 28x28 images)
    tti.add(TimeDistributed(Dense(784, activation='relu')))  # Flattened 28x28 image (784)

    # Reshape the 784-dim vector into a 28x28 image (using TimeDistributed)
    tti.add(TimeDistributed(Reshape((28, 28, 1))))  # Reshape to 28x28x1 image

    # Add transposed convolution layers (Conv2DTranspose) to generate images from the latent vector
    tti.add(TimeDistributed(Conv2DTranspose(128, (3, 3), strides=(1, 1), padding='same', activation='relu')))
    tti.add(TimeDistributed(Conv2DTranspose(64, (3, 3), strides=(1, 1), padding='same', activation='relu')))

    # Final output layer to generate a 28x28 image for each time step
    tti.add(TimeDistributed(Conv2DTranspose(1, (3, 3), padding='same', activation='sigmoid')))

    # Add ConvLSTM2D layer (for sequence generation)
    tti.add(ConvLSTM2D(filters=1, kernel_size=(3, 3), strides=(1, 1), return_sequences=True, padding='same'))

    # Compile the model
    tti.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

    # Print the model summary
    tti.summary()

    return tti

texttoimage_deconvolutional=texttoimage_deconvo()
texttoimage_separate=texttoimage_separate()
toimg_vector=texttoimage_vector()
toimg_sequential_deconvolutional=texttoimage_decode_encode_deconvolutional()
toimg_convolstm=texttoimage_convolstm()

"""<h1>Two part model</h2>"""

# Since the two part model is firstly trained to generate hidden vectors from text to text we need to train t2t model first
def build_text2text_model():
    text2text = tf.keras.Sequential()

    text2text.add(LSTM(256, input_shape=(None, len(unique_characters)), return_sequences=False))
    text2text.add(RepeatVector(3))
    text2text.add(LSTM(256, return_sequences=True))
    text2text.add(TimeDistributed(Dense(len(unique_characters), activation='softmax')))
    text2text.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    text2text.summary()

    return text2text

X_ttt_train_90, X_ttt_test_90, y_ttt_train_90,y_ttt_test_90=split_xy(X_text_onehot,y_text_onehot,0.9)
t2t=build_text2text_model()
t2t.fit(X_ttt_train_90, y_ttt_train_90, batch_size=64, epochs=30)

two_part_model=two_part_text_to_image(t2t)

"""<h1>Train-Test split</h1>"""

X_tti_train_90, X_tti_test_90, y_tti_train_90,y_tti_test_90=split_xy(X_text_onehot,y_img,0.9)

X_tti_train,y_tti_train=augment_data(X_tti_train_90,y_tti_train_90,10)
sample_indices = [3, 15, 42, 58, 97]
predictor = EpochEndPredictor(sample_indices, X_tti_train, y_tti_train,decode_labels)
print(X_tti_train.shape)
print(y_tti_train.shape)

# split for the sepearate deconvolutional layer output
y_img_digit_1 = y_tti_train[:, 0, :, :]
y_img_digit_2 = y_tti_train[:, 1, :, :]
y_img_digit_3 = y_tti_train[:, 2, :, :]

"""<h1>Trainning</h1>"""

deconvolutional=texttoimage_deconvolutional.fit(X_tti_train,y_tti_train,batch_size=64, epochs=30,  callbacks=[predictor])

deconvolutional_separate=texttoimage_separate.fit(X_tti_train,[y_img_digit_1, y_img_digit_2, y_img_digit_3],batch_size=64, epochs=30)

lstm_only=toimg_vector.fit(X_tti_train,y_tti_train,batch_size=64, epochs=30,  callbacks=[predictor])

simple_deconvolutional=toimg_sequential_deconvolutional.fit(X_tti_train, y_tti_train, batch_size=64, epochs=30)

sequential_convolutional=toimg_convolstm.fit(X_tti_train, y_tti_train, batch_size=64, epochs=30)

two_part=two_part_model.fit(X_tti_train, y_tti_train, batch_size=64, epochs=30)

print(X_tti_train.shape,X_ttt_train_90.shape)

"""<h1>Model outputs on the test set</h1>"""



#deconvolutional values
values_deconv=texttoimage_deconvolutional.predict(X_tti_test_90)

#seperate model values
values_seperate=texttoimage_separate.predict(X_tti_test_90)
values_seperate = np.array(values_seperate)

#simple lstm vector values
values_vector=toimg_vector.predict(X_tti_test_90)

#sequence deconvo
values_seq=toimg_sequential_deconvolutional.predict(X_tti_test_90)


#convolutional sequence
values_convolstm=toimg_convolstm.predict(X_text_onehot)

# # 2 part model prediction
# values_two_part=two_part.predict(X_tti_test_90)

plot_prediction(X_tti_test_90,values_deconv,100)

plot_prediction_separate(X_tti_test_90,values_seperate,100)

plot_prediction(X_tti_test_90,values_vector,100)

plot_prediction(X_tti_test_90,values_seq,100)

plot_prediction(X_tti_test_90,values_convolstm,100)

# 2 part model prediction
values_two_part=two_part_model.predict(X_tti_test_90)
plot_prediction(X_tti_test_90,values_two_part,100)

