# -*- coding: utf-8 -*-
"""RL_assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yWP-LztkZnFidvU9L_bMlHbqJjWU8MQg
"""

#incompatibility with gym downgrade to 1.23.5 works
!pip install numpy==1.23.5

#Naive DQN implementation
import gym
import torch
import torch.nn as nn
import torch.optim as optim
import random
import numpy as np
import matplotlib.pyplot as plt


#NN 1 hidden layer
class DQN(nn.Module):
  def __init__(self, input, output):
    super(DQN, self).__init__()
    self.fc1 = nn.Linear(input, 128)
    self.out = nn.Linear(128, output)

  def forward(self, x):
    x = torch.relu(self.fc1(x))
    return self.out(x)


def select_action(state, epsilon):
  if random.random() < epsilon:
    return env.action_space.sample()
  else:
    state_tensor = torch.FloatTensor(state).unsqueeze(0)
    return torch.argmax(model(state_tensor)).item()

def moving_average(values, window=50):
    return np.convolve(values, np.ones(window)/window, mode='valid')

#hyperparameters
gamma = 0.99
learning_rate = 0.001
epsilon_min = 0.01
epsilon_decay = 0.995
num_episodes = 1000
num_runs = 5

#initialization
env = gym.make('CartPole-v1')
state_dim = env.observation_space.shape[0]
action_dim = env.action_space.n


all_rewards_models = []
all_rewards = []
all_steps = []

#multiple runs
for run in range(num_runs):
  epsilon = 1.0
  model = DQN(state_dim, action_dim)
  optimizer = optim.Adam(model.parameters(), lr=learning_rate)
  loss_fn = nn.MSELoss()
  rewards = []

  for episode in range(num_episodes):
    state = env.reset()
    total_reward_episode = 0
    steps = 0
    while True:
      action = select_action(state, epsilon)
      next_state, reward, done, _,= env.step(action)
      total_reward_episode += reward
      steps += 1

      # Compute target
      next_state_tensor = torch.FloatTensor(next_state).unsqueeze(0)
      state_tensor = torch.FloatTensor(state).unsqueeze(0)
      target = reward + (gamma * torch.max(model(next_state_tensor)).item() * (1 - done))

      # Compute loss
      q_value = model(state_tensor)[0, action]
      loss = loss_fn(q_value, torch.tensor(target))

      optimizer.zero_grad()
      loss.backward()
      optimizer.step()

      state = next_state
      if done:
        break
    epsilon = max(epsilon_min, epsilon * epsilon_decay)
    rewards.append(total_reward_episode)

    print(f"Run: {run + 1}, Episode {episode + 1}, Total Reward: {total_reward_episode}, Epsilon: {epsilon:.4f}")

  all_rewards.append(rewards)



env.close()

mean_rewards = np.mean(all_rewards, axis=0)
smoothed_mean = moving_average(mean_rewards, window=10)

#learning curve
plt.figure(figsize=(12, 6))
for run in range(num_runs):
  smoothed_run = moving_average(all_rewards[run], window=10)
  plt.plot(smoothed_run,label=f'Run {run+1}')

plt.plot(smoothed_mean, color='black', linewidth=2, label="Mean Reward")

plt.xlabel('Number of Episodes')
plt.ylabel(f'Average Return over Environment Steps for {num_runs} runs')
plt.title('Learning Curve (Return over Environment Steps)')
plt.legend()
plt.show()

#DQN ablation study
import itertools
import gym
import torch
import torch.nn as nn
import torch.optim as optim
import random
import numpy as np
import matplotlib.pyplot as plt
learning_rates = [0.001, 0.0001, 0.00001]
update_ratios = [1, 5, 10]
network_sizes = [32, 64, 128]
epsilon_decays = [0.995,0.99,0.985]

#NN 1 hidden layer
class DQN(nn.Module):
  def __init__(self, input, output,net_size):
    super(DQN, self).__init__()
    self.fc1 = nn.Linear(input, net_size)
    self.out = nn.Linear(net_size, output)

  def forward(self, x):
    x = torch.relu(self.fc1(x))
    return self.out(x)


def select_action(state, epsilon):
  if random.random() < epsilon:
    return env.action_space.sample()
  else:
    state_tensor = torch.FloatTensor(state).unsqueeze(0)
    return torch.argmax(model(state_tensor)).item()


#initialization
env = gym.make('CartPole-v1')
state_dim = env.observation_space.shape[0]
action_dim = env.action_space.n

for lr, update_ratio, net_size, eps_decay in itertools.product(learning_rates,update_ratios, network_sizes, epsilon_decays):
  print(f"Running Experiment: LR={lr}, Update Ratio={update_ratio}, Network Size={net_size}, Eps Decay={eps_decay}")


  #hyperparameters
  gamma = 0.99
  learning_rate = lr
  epsilon_min = 0.01
  epsilon_decay = eps_decay
  num_episodes = 1000
  epsilon = 1.0



  model = DQN(state_dim, action_dim,net_size)
  optimizer = optim.Adam(model.parameters(), lr=learning_rate)
  loss_fn = nn.MSELoss()

  all_rewards = []

  for episode in range(num_episodes):

    state = env.reset()
    total_reward_episode = 0
    steps = 0
    while True:
      action = select_action(state, epsilon)
      next_state, reward, done, _,= env.step(action)
      total_reward_episode += reward
      steps += 1

      if steps % update_ratio == 0:
        next_state_tensor = torch.FloatTensor(next_state).unsqueeze(0)
        state_tensor = torch.FloatTensor(state).unsqueeze(0)
        target = reward + (gamma * torch.max(model(next_state_tensor)).item() * (1 - done))

        q_value = model(state_tensor)[0, action]
        loss = loss_fn(q_value, torch.tensor(target))

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

      state = next_state
      if done:
        break
    epsilon = max(epsilon_min, epsilon * epsilon_decay)
    all_rewards.append(total_reward_episode)

  mean_rewards = np.mean(all_rewards, axis=0)

  print(f"Mean Reward: {mean_rewards}")
env.close()

#Naive DQN implementation with fixed hyperparameters
import gym
import torch
import torch.nn as nn
import torch.optim as optim
import random
import numpy as np
import matplotlib.pyplot as plt


#NN 1 hidden layer
class DQN(nn.Module):
  def __init__(self, input, output):
    super(DQN, self).__init__()
    self.fc1 = nn.Linear(input, 128)
    self.out = nn.Linear(128, output)

  def forward(self, x):
    x = torch.relu(self.fc1(x))
    return self.out(x)


def select_action(state, epsilon):
  if random.random() < epsilon:
    return env.action_space.sample()
  else:
    state_tensor = torch.FloatTensor(state).unsqueeze(0)
    return torch.argmax(model(state_tensor)).item()

def moving_average(values, window):
    return np.convolve(values, np.ones(window)/window, mode='valid')

#hyperparameters
gamma = 0.99
learning_rate = 0.001
epsilon_min = 0.01
epsilon_decay = 0.99
num_episodes = 1000
num_runs = 5

#initialization
env = gym.make('CartPole-v1')
state_dim = env.observation_space.shape[0]
action_dim = env.action_space.n


all_rewards_models = []
all_rewards = []
all_steps = []

#multiple runs
for run in range(num_runs):
  epsilon = 1.0
  model = DQN(state_dim, action_dim)
  optimizer = optim.Adam(model.parameters(), lr=learning_rate)
  loss_fn = nn.MSELoss()
  rewards = []

  for episode in range(num_episodes):
    state = env.reset()
    total_reward_episode = 0
    steps = 0
    while True:
      action = select_action(state, epsilon)
      next_state, reward, done, _,= env.step(action)
      total_reward_episode += reward
      steps += 1

      # Compute target
      next_state_tensor = torch.FloatTensor(next_state).unsqueeze(0)
      state_tensor = torch.FloatTensor(state).unsqueeze(0)
      target = reward + (gamma * torch.max(model(next_state_tensor)).item() * (1 - done))

      # Compute loss
      q_value = model(state_tensor)[0, action]
      loss = loss_fn(q_value, torch.tensor(target))

      optimizer.zero_grad()
      loss.backward()
      optimizer.step()

      state = next_state
      if done:
        break
    epsilon = max(epsilon_min, epsilon * epsilon_decay)
    rewards.append(total_reward_episode)

    print(f"Run: {run + 1}, Episode {episode + 1}, Total Reward: {total_reward_episode}, Epsilon: {epsilon:.4f}")

  all_rewards.append(rewards)



env.close()

mean_rewards = np.mean(all_rewards, axis=0)
smoothed_mean = moving_average(mean_rewards, window=10)

all_rewards_models.append([smoothed_mean,'Naive'])

#learning curve
plt.figure(figsize=(12, 6))
for run in range(num_runs):
  smoothed_run = moving_average(all_rewards[run], window=10)
  plt.plot(smoothed_run,label=f'Run {run+1}')

plt.plot(smoothed_mean, color='black', linewidth=2, label="Mean Reward")

plt.xlabel('Number of Episodes')
plt.ylabel(f'Average Return over Environment Steps for {num_runs} runs')
plt.title('Learning Curve (Return over Environment Steps)')
plt.legend()
plt.show()

from collections import deque

#DQN with ER
#NN 1 hidden layer
class DQN(nn.Module):
  def __init__(self, input, output):
    super(DQN, self).__init__()
    self.fc1 = nn.Linear(input, 128)
    self.out = nn.Linear(128, output)

  def forward(self, x):
    x = torch.relu(self.fc1(x))
    return self.out(x)


def select_action(state, epsilon):
  if random.random() < epsilon:
    return env.action_space.sample()
  else:
    state_tensor = torch.FloatTensor(state).unsqueeze(0)
    return torch.argmax(model(state_tensor)).item()

def moving_average(values, window=50):
    return np.convolve(values, np.ones(window)/window, mode='valid')

#hyperparameters
gamma = 0.99
learning_rate = 0.001
epsilon_min = 0.01
epsilon_decay = 0.99
num_episodes = 1000
num_runs = 5

#buffer and minibatch
batch_size = 100
buffer_size = 10000
replay_buffer = deque(maxlen=buffer_size)

#initialization
env = gym.make('CartPole-v1')
state_dim = env.observation_space.shape[0]
action_dim = env.action_space.n



all_rewards = []
all_steps = []

#multiple runs
for run in range(num_runs):
  epsilon = 1.0
  model = DQN(state_dim, action_dim)
  optimizer = optim.Adam(model.parameters(), lr=learning_rate)
  loss_fn = nn.MSELoss()
  rewards_run = []

  for episode in range(num_episodes):
    state = env.reset()
    total_reward_episode = 0
    steps = 0
    while True:
      action = select_action(state, epsilon)
      next_state, reward, done, _,= env.step(action)
      total_reward_episode += reward
      steps += 1


      replay_buffer.append((state, action, reward, next_state, done))

      if len(replay_buffer)>=batch_size:
        #minibatch sample
        states, actions, rewards, next_states, dones = zip(*random.sample(replay_buffer, batch_size))
        states = torch.FloatTensor(states)
        actions = torch.LongTensor(actions)
        rewards = torch.FloatTensor(rewards)
        next_states = torch.FloatTensor(next_states)
        dones = torch.FloatTensor(dones)

        #compute targets
        next_q_values = model(next_states).max(1)[0].detach()
        targets = rewards + gamma * next_q_values * (1 - dones)

        #compute loss
        q_values = model(states).gather(1, actions.unsqueeze(1)).squeeze()
        loss = loss_fn(q_values, targets)

        #optimize
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

      state = next_state
      if done:
        break


    epsilon = max(epsilon_min, epsilon * epsilon_decay)
    rewards_run.append(total_reward_episode)

    print(f"Run: {run + 1}, Episode {episode + 1}, Total Reward: {total_reward_episode}, Epsilon: {epsilon:.4f}")

  all_rewards.append(rewards_run)



env.close()

mean_rewards = np.mean(all_rewards, axis=0)
smoothed_mean = moving_average(mean_rewards, window=10)
all_rewards_models.append([smoothed_mean,'ER'])

#learning curve
plt.figure(figsize=(12, 6))
for run in range(num_runs):
  smoothed_run = moving_average(all_rewards[run], window=10)
  plt.plot(smoothed_run,label=f'Run {run+1}')

plt.plot(smoothed_mean, color='black', linewidth=2, label="Mean Reward")

plt.xlabel('Number of Episodes')
plt.ylabel(f'Average Return over Environment Steps for {num_runs} runs')
plt.title('Learning Curve (Return over Environment Steps)')
plt.legend()
plt.show()

#DQN with TN implementation
import gym
import torch
import torch.nn as nn
import torch.optim as optim
import random
import numpy as np
import matplotlib.pyplot as plt

#NN 1 hidden layer
class DQN(nn.Module):
  def __init__(self, input, output):
    super(DQN, self).__init__()
    self.fc1 = nn.Linear(input, 128)
    self.out = nn.Linear(128, output)

  def forward(self, x):
    x = torch.relu(self.fc1(x))
    return self.out(x)


def select_action(state, epsilon):
  if random.random() < epsilon:
    return env.action_space.sample()
  else:
    state_tensor = torch.FloatTensor(state).unsqueeze(0)
    return torch.argmax(model(state_tensor)).item()

def moving_average(values, window):
    return np.convolve(values, np.ones(window)/window, mode='valid')

#hyperparameters
gamma = 0.99
learning_rate = 0.001
epsilon_min = 0.01
epsilon_decay = 0.99
num_episodes = 1000
num_runs = 5
target_update_freq = 10

#initialization
env = gym.make('CartPole-v1')
state_dim = env.observation_space.shape[0]
action_dim = env.action_space.n



all_rewards = []
all_steps = []

#multiple runs
for run in range(num_runs):
  epsilon = 1.0
  model = DQN(state_dim, action_dim)

  #target network initizlize copying the qnet
  target_net = DQN(state_dim, action_dim)
  target_net.load_state_dict(model.state_dict())

  #set to evaluation mode no training
  target_net.eval()

  optimizer = optim.Adam(model.parameters(), lr=learning_rate)
  loss_fn = nn.MSELoss()
  rewards = []

  for episode in range(num_episodes):
    state = env.reset()
    total_reward_episode = 0
    while True:
      action = select_action(state, epsilon)
      next_state, reward, done, _,= env.step(action)
      total_reward_episode += reward

      #compute target using target net
      next_state_tensor = torch.FloatTensor(next_state).unsqueeze(0)
      state_tensor = torch.FloatTensor(state).unsqueeze(0)
      target_net_next = torch.max(target_net(next_state_tensor)).item()
      target = reward + (gamma * target_net_next * (1 - done))

      #compute loss
      q_value = model(state_tensor)[0, action]
      loss = loss_fn(q_value, torch.tensor(target))

      optimizer.zero_grad()
      loss.backward()
      optimizer.step()


      state = next_state
      if done:
        break
    #update target net
    if episode % target_update_freq == 0:
      target_net.load_state_dict(model.state_dict())
    epsilon = max(epsilon_min, epsilon * epsilon_decay)
    rewards.append(total_reward_episode)

    print(f"Run: {run + 1}, Episode {episode + 1}, Total Reward: {total_reward_episode}, Epsilon: {epsilon:.4f}")

  all_rewards.append(rewards)



env.close()

mean_rewards = np.mean(all_rewards, axis=0)
smoothed_mean = moving_average(mean_rewards, window=10)
all_rewards_models.append([smoothed_mean,'TN'])

#learning curve
plt.figure(figsize=(12, 6))
for run in range(num_runs):
  smoothed_run = moving_average(all_rewards[run], window=10)
  plt.plot(smoothed_run,label=f'Run {run+1}')

plt.plot(smoothed_mean, color='black', linewidth=2, label="Mean Reward")

plt.xlabel('Number of Episodes')
plt.ylabel(f'Average Return over Environment Steps for {num_runs} runs')
plt.title('Learning Curve (Return over Environment Steps)')
plt.legend()
plt.show()

#DQN with TN and ER
import gym
import torch
import torch.nn as nn
import torch.optim as optim
import random
import numpy as np
import matplotlib.pyplot as plt
from collections import deque

all_rewards_models = []
#NN 1 hidden layer
class DQN(nn.Module):
  def __init__(self, input, output):
    super(DQN, self).__init__()
    self.fc1 = nn.Linear(input, 128)
    self.out = nn.Linear(128, output)

  def forward(self, x):
    x = torch.relu(self.fc1(x))
    return self.out(x)


def select_action(state, epsilon):
  if random.random() < epsilon:
    return env.action_space.sample()
  else:
    state_tensor = torch.FloatTensor(state).unsqueeze(0)
    return torch.argmax(model(state_tensor)).item()

def moving_average(values, window):
    return np.convolve(values, np.ones(window)/window, mode='valid')

#hyperparameters
gamma = 0.99
learning_rate = 0.001
epsilon_min = 0.01
epsilon_decay = 0.99
num_episodes = 1000
num_runs = 5
target_update_freq = 10

#initialization
env = gym.make('CartPole-v1')
state_dim = env.observation_space.shape[0]
action_dim = env.action_space.n

#buffer and minibatch
batch_size = 100
buffer_size = 10000
replay_buffer = deque(maxlen=buffer_size)

all_rewards = []
all_steps = []

#multiple runs
for run in range(num_runs):
  epsilon = 1.0
  model = DQN(state_dim, action_dim)

  #target network initizlize coping the qnet
  target_net = DQN(state_dim, action_dim)
  target_net.load_state_dict(model.state_dict())

  #set to evaluation mode no training
  target_net.eval()

  optimizer = optim.Adam(model.parameters(), lr=learning_rate)
  loss_fn = nn.MSELoss()
  rewards_run = []

  for episode in range(num_episodes):
    state = env.reset()
    total_reward_episode = 0
    while True:
      action = select_action(state, epsilon)
      next_state, reward, done, _,= env.step(action)
      total_reward_episode += reward

      replay_buffer.append((state, action, reward, next_state, done))

      if len(replay_buffer)>=batch_size:
        #minibatch sample
        states, actions, rewards, next_states, dones = zip(*random.sample(replay_buffer, batch_size))
        states = torch.FloatTensor(states)
        actions = torch.LongTensor(actions)
        rewards = torch.FloatTensor(rewards)
        next_states = torch.FloatTensor(next_states)
        dones = torch.FloatTensor(dones)

        #compute targets using target net
        next_q_values = target_net(next_states).max(1)[0].detach()
        targets = rewards + gamma * next_q_values * (1 - dones)

        #compute loss
        q_values = model(states).gather(1, actions.unsqueeze(1)).squeeze()
        loss = loss_fn(q_values, targets)

        #optimize
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()


      state = next_state
      if done:
        break
    #update target net
    if episode % target_update_freq == 0:
      target_net.load_state_dict(model.state_dict())
    epsilon = max(epsilon_min, epsilon * epsilon_decay)
    rewards_run.append(total_reward_episode)

    print(f"Run: {run + 1}, Episode {episode + 1}, Total Reward: {total_reward_episode}, Epsilon: {epsilon:.4f}")

  all_rewards.append(rewards_run)



env.close()

mean_rewards = np.mean(all_rewards, axis=0)
smoothed_mean = moving_average(mean_rewards, window=10)
all_rewards_models.append([smoothed_mean,'ER and TN'])

#learning curve
plt.figure(figsize=(12, 6))
for run in range(num_runs):
  smoothed_run = moving_average(all_rewards[run], window=10)
  plt.plot(smoothed_run,label=f'Run {run+1}')

plt.plot(smoothed_mean, color='black', linewidth=2, label="Mean Reward")

plt.xlabel('Number of Episodes')
plt.ylabel(f'Average Return over Environment Steps for {num_runs} runs')
plt.title('Learning Curve (Return over Environment Steps)')
plt.legend()
plt.show()

!python -m pip freeze > requirements.txt